### ISSUE TITLE
Nested Table Rendering Issue

### ISSUE THREAD

**Issue by Mint2K** [dompdf/dompdf#1741] opened 2018-05-22 10:27 UTC
When rendering the following markup, any subsequent content appears directly below the first TD in the outer table even if the second TD is taller as a result of the nested table. This results in overlapping with the second TD and subsequent content. Any idea why this might be?

I'm using version: <5113accd>

Thanks

```
<table class="info">
    		<tr>
    			<td style="vertical-align: top;">
			</td>
			<td style="vertical-align:top;">
				<table style="margin-left: auto; margin-right: 0;">
					<tr>
						<td>
						</td>
						<td>
    						</td>
    					</tr>
    				</table>
			</td>
		</tr>
</table>
```

**Comment by EllanTseyeth** [comment] 2018-06-26 11:05
I have this issue too, here is a version of a generated PDF file to give more meat to this issue in the hopes it gets fixed! 🤞.

[20180000017_35a95a506b16f5_6AFAF740-B865-41A3-8208-44ED677425B5.pdf](https://github.com/dompdf/dompdf/files/2136841/20180000017_35a95a506b16f5_6AFAF740-B865-41A3-8208-44ED677425B5.pdf)

Here is my call:
```
                // instantiate and use the dompdf class
		$dompdf = new Dompdf();
		$dompdf->set_option('isHtml5ParserEnabled', true);
		$dompdf->loadHtml($html);

		// (Optional) Setup the paper size and orientation
		$dompdf->setPaper('Legal', 'landscape');
		
		// Render the HTML as PDF
		$dompdf->render();
		//$dompdf->set_base_path('localhost/exampls/style.css');
		// Output the generated PDF to file
		file_put_contents($filename, $dompdf->output());
```

I'm using Smarty template engine inside Koseven framework with bootstrap 3.
I nested my nested tables inside divs in the hope to fix this, but it didn't do the trick.

```
<!-- Invoice template -->

<div class="table-responsive">
  <table cellspacing="0" cellpadding="0" align="left" border="1" class="table table-bordered table-sm table-responsive">
    <thead class="thead-dark">
      <tr>
        <th colspan="2">
			<h6 class="panel-title"><!--{Kohana_lang string=payment_checkout_title2}--></h6>
        </th>
      </tr>
    </thead>
    <tbody>
      <tr>
		  <td>
        <div class="table-responsive">
          <table cellspacing="0" cellpadding="0" align="left" border="1" class="table table-bordered table-sm table-responsive">
            <tbody>
              <tr>
                <td><img src="<!--{$image_src}-->sook_media_logo_black.png" class="content-group mt-10" alt="Sook Media" style="width: 120px;"/> 
                  <!--{if isset($a_business) && !empty($a_business)}-->
                  
                  <ul class="list-condensed list-unstyled">
                    <li><!--{$a_business.address}--></li>
                    <li><!--{$a_business.city}-->, <!--{$a_business.province}-->, <!--{$a_business.country}--></li>
                    <li><!--{$a_business.zip_code}--></li>
                    <li><!--{$a_business.phone}--></li>
                  </ul>
                  
                  <!--{else}-->
                  
                  <div class="mb-15 mt-15"><!--{Kohana_lang string=payment_checkout_unavailable}--></div>
                  
                  <!--{/if}-->
				 </td>
                <td align="right">
					<div class="invoice-details"> 
						<!--{if $paid}--> 
						<!--{assign var="invoice" value="<!--{Kohana_lang string=payment_checkout_invoice}-->"}--> 
						<!--{else}--> 
						<!--{assign var="invoice" value="<!--{Kohana_lang string=payment_checkout_estimate}-->"}--> 
						<!--{/if}-->
						<h5 class="text-uppercase text-muted"><!--{$invoice}--><!--{$a_cart.idempotency}--></h5>
						<!--{if $paid}--> 
						<span class="text-uppercase text-semibold"><!--{Kohana_lang string=payment_checkout_sequence}--><!--{$a_cart.sequencial}--></span> 
						<!--{/if}-->
						<ul class="list-condensed list-unstyled">
						  <li><!--{Kohana_lang string=payment_checkout_date_initiated}--><span class="text-semibold"><!--{$a_cart.creation_date}--></span></li>
						  <li><!--{Kohana_lang string=payment_checkout_date_closed}--><span class="text-semibold"><!--{$a_cart.modification_date}--></span></li>
						  <li><!--{Kohana_lang string=payment_checkout_date_due}--><span class="text-semibold"><!--{$a_cart.modification_date}--></span></li>
						</ul>
					  </div>
				  </td>
              </tr>
            </tbody>
          </table>
        </div>
        <div class="table-responsive">
          <table cellspacing="0" cellpadding="0" align="left" border="1" class="table table-bordered table-sm table-responsive">
            <tbody>
              <tr>
                <td><span class="text-muted"><!--{Kohana_lang string=payment_checkout_invoiced_to}--></span> 
                  <!--{if isset($a_cart.contact.element_name) && !empty($a_cart.contact.element_name)}--> 
                  <!--{assign var="elem_name" value=$a_cart.contact.element_name}--> 
                  <!--{assign var="address" value=$a_cart.contact.address}--> 
                  <!--{else}--> 
                  <!--{assign var="elem_name" value=""}--> 
                  <!--{assign var="address" value=""}--> 
                  <!--{/if}-->
                  
                  <ul class="list-condensed list-unstyled">
                    <li>
                      <h5><!--{$a_cart.contact.first_name}--> <!--{$a_cart.contact.last_name}--></h5>
                    </li>
                    <li><span class="text-semibold"><!--{$elem_name}--></span></li>
                    <li><!--{$a_cart.contact.address}--></li>
                    <li><a href="mailto:<!--{$a_cart.contact.email}-->"><!--{$a_cart.contact.email}--></a></li>
                  </ul>
				</td>
                <td align="right"><span class="text-muted"><!--{Kohana_lang string="payment_checkout_payment_detail"}--></span>
                  <ul class="list-condensed list-unstyled invoice-payment-details">
                    <li>
                      <h5><!--{Kohana_lang string="payment_checkout_total3"}--><span id="checkout_total2" class="text-right text-semibold"><!--{$a_cart.total}-->$</span></h5>
                    </li>
                  </ul>
				</td>
              </tr>
            </tbody>
          </table>
        </div>
		</td>
      </tr>
      <tr>
		  <td>
        <div class="table-responsive">
          <table cellspacing="0" cellpadding="0" align="left" border="1" id="table_checkout" class="table table-striped table-bordered table-sm table-responsive">
            <thead class="thead-dark">
              <tr>
                <th class="col-sm-8"><!--{Kohana_lang string=payment_checkout_description}--></th>
                <th class="col-sm-1"><!--{Kohana_lang string=payment_checkout_recurrence}--></th>
                <th class="col-sm-1"><!--{Kohana_lang string=payment_checkout_price}--></th>
                <th class="col-sm-1"><!--{Kohana_lang string=payment_checkout_quantity}--></th>
                <th class="col-sm-1"><!--{Kohana_lang string=payment_checkout_total}--></th>
                <!--{if !$paid && (!isset($item_read_only) || (isset($item_read_only) && !$item_read_only))}-->
                <th></th>
                <!--{/if}--> 
              </tr>
            </thead>
            <tbody>
              <!--{if isset($a_data)}--> 
              <!--{foreach from=$a_data key=key item=value}--> 
              <!--{if isset($a_cart.a_item.$key) && !is_null($a_cart.a_item.$key)}-->
              <tr id="row_<!--{$key}-->"> 
                <!--{if $key === 'subscription'}--> 
                <!--{assign var=the_id value="id='header_<!--{$key}-->' "}--> 
                <!--{else}--> 
                <!--{assign var=the_id value=""}--> 
                <!--{/if}-->
                <td><h6 <!--{$the_id}-->class="no-margin"><!--{$value.title}--></h6>
                  <span class="text-muted"><!--{$value.description1}--><!--{$value.description2}--></span>
			  	</td>
                <!--{assign var=recurrence value=$value.recurrence}-->
                <td><!--{$recurrence}--></td>
                <td><!--{$value.price}--></td>
                <td><!--{$value.qty}--></td>
                <td><span class="text-semibold"><!--{$value.total_line}--> $</span></td> 
              </tr>
              <!--{if isset($value.coupon) && !is_null($value.coupon)}-->
              <tr id="coupon_<!--{$key}-->">
                <td class="text-right"><h6 class="no-margin"><!--{Kohana_lang string=payment_checkout_rebate_title}--></h6>
                  <span class="text-muted"><!--{Kohana_lang string=payment_checkout_rebate_text}--><!--{$value.coupon.code}--></span></td>
                <td><!--{$value.coupon.recurrence}--></td>
                <td><!--$value.coupon.value--></td>
                <td></td>
                <td><span class="text-semibold">(<!--{$value.coupon.total}-->)$</span></td>
              </tr>
              <!--{/if}--> 
              <!--{/if}--> 
              <!--{/foreach}--> 
              <!--{/if}-->
            </tbody>
          </table>
        </div>
</td>
      </tr>
      <tr>
		  <td>
        <div class="table-responsive">
          <table cellspacing="0" cellpadding="0" align="left" border="1" class="table table-bordered table-sm table-responsive">
            <tbody>
              <tr>
                <td>
					<h6><!--{Kohana_lang string=payment_checkout_authorized_person}--></h6>
                  
                  <!--{if isset($a_business) && !empty($a_business)}-->
                  
                  <div class="mb-15 mt-15"> <img src="<!--{$image_src}-->signature.png" class="display-block" style="width: 150px;" alt=""> </div>
                  <ul class="list-condensed list-unstyled text-muted">
                    <li><!--{$a_business.name}--></li>
                    <li><!--{$a_business.address}--></li>
                    <li><!--{$a_business.city}-->, <!--{$a_business.province}-->, <!--{$a_business.country}--></li>
                    <li><!--{$a_business.zip_code}--></li>
                  </ul>
                  
                  <!--{else}-->
                  
                  <div class="mb-15 mt-15"><!--{Kohana_lang string=payment_checkout_unavailable}--></div>
                  
                  <!--{/if}-->
				</td>
                <td align="right">
					<div class="table-responsive">
                    <table cellspacing="0" cellpadding="0" align="left" border="1" class="table table-bordered table-sm table-responsive">
                      <thead>
                        <tr>
                          <th>
							  <h6><!--{Kohana_lang string="payment_checkout_total_due"}--></h6>
                          </th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr>
                          <th><!--{Kohana_lang string="payment_checkout_subtotal"}--></th>
                          <td id='checkout_subtotal' class="text-right"><!--{$a_cart.subtotal}-->$</td>
                        </tr>
                        <tr>
                          <th><!--{Kohana_lang string="payment_checkout_taxes"}--><span class="text-regular">(<!--{$a_cart.tax_rate}-->%)</span></th>
                          <td id='checkout_tax_amount' class="text-right"><!--{$a_cart.tax_amount}-->$</td>
                        </tr>
                        <tr>
                          <th><!--{Kohana_lang string="payment_checkout_discount"}--></th>
                          <td id='checkout_rebate_total' class="text-right"><!--{$a_cart.rebate_total}-->$</td>
                        </tr>
                        <tr>
                          <th><!--{Kohana_lang string="payment_checkout_credit"}--></th>
                          <td id='checkout_applied_credit' class="text-right"><!--{$a_cart.applied_credit}-->$</td>
                        </tr>
                        <tr>
                          <th><!--{Kohana_lang string="payment_checkout_total2"}--></th>
                          <td class="text-right text-primary"><h5 id='checkout_total' class="text-semibold"><!--{$a_cart.total}-->$</h5></td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
				</td>
              </tr>
            </tbody>
          </table>
        </div>
			  </td>
      </tr>
    </tbody>
    <tfoot>
      <tr>
		<td>
          <h6><!--{Kohana_lang string=payment_checkout_subtitle}--></h6>
          <p class="text-muted"><!--{Kohana_lang string=payment_checkout_other_information}--></p>
          <p class="text-muted"><!--{Kohana_lang string=payment_checkout_other_disclaimer}--></p>
		</td>
      </tr>
    </tfoot>
  </table>
</div>
<!-- /invoice template -->
```

**Comment by bsweeney** [comment] 2018-06-27 00:38
Probably the same issue as noted in #1482. Dompdf seems to be having an issue laying out elements (tables specifically?) with `auto` width plus `auto` margin.

@EllanTseyeth Dompdf can be finicky about your document's syntax. So a good first crack at debugging is to run your document through an HTML validator.

**Comment by bsweeney** [comment] 2021-12-07 00:43
I don't have a good sample for reproducing the issue. Significant improvements have been made to table rendering so I'm closing unless we get additional information.

**Closed by bsweeney** 2021-12-07 00:43 UTC
Labels: bug, On Deck, css, layout
