### ISSUE TITLE
Regression bug with set_font_size / single_length_in_pt

### ISSUE THREAD

**Issue by MrTrick** [dompdf/dompdf#2771] opened 2022-02-09 17:10 UTC
**Platform Info**
* PHP 7.2.26
* dompdf 1.1.1 -> 1.2.0
* Alpine Linux 10.2.1

**What Happened?**
When I updated from dompdf v1.1.1 to v1.2.0, my project unit tests began failing with:
```
TypeError: Argument 2 passed to Dompdf\Css\Style::single_length_in_pt() must be of the type float, string given, called in /data/vendor/dompdf/dompdf/src/Css/Style.php on line 2492

/data/vendor/dompdf/dompdf/src/Css/Style.php:811
/data/vendor/dompdf/dompdf/src/Css/Style.php:2492
/data/vendor/dompdf/dompdf/src/Css/Style.php:1319
/data/vendor/dompdf/dompdf/src/Css/Style.php:913
/data/vendor/dompdf/dompdf/src/Css/Stylesheet.php:1099
...
```

**What Do I Think Is Wrong?**
* In Style.php, `single_length_in_pt()` is called from `set_font_size()`.
* If `set_font_size()` is given a float value for `$size`, it will be passed as-is through to `single_length_in_pt()`
(Maybe `single_length_in_pt()` should also accept a float parameter?)

**Are You Freaking Out?**
For now I've downgraded back to v1.1.1, and the unit tests are again passing.
It's not causing me any urgent difficulty. 😉

**Comment by mipel85** [comment] 2022-02-11 15:10
Hello, 
in the same way, I also had an error on line 851 of the style.php file because it seems that it would be necessary to force the type of the $font_size variable recognized as string.
I modified like this:
[Style.php.zip](https://github.com/dompdf/dompdf/files/8049614/Style.php.zip)

elseif (($i = mb_stripos($l, "em")) !== false) {
             $value = (float)mb_substr($l, 0, $i) ***(float)**$font_size;
         }
  This solves the problem for me and allows me to generate readable pdf files.
While waiting for more information, I hope it will help.
Michel

**Comment by bsweeney** [comment] 2022-02-11 15:25
@MrTrick I appreciate the lack of freaking out.

Is this something that's being encountered during rendering, or only with unit tests? I'm unable to reproduce while rendering a document, so if anyone has a sample that would be helpful.

**Comment by mipel85** [comment] 2022-02-12 09:33
Hi,
When I run a rendering test, this error occurs on line 851:
```
TypeError
Unsupported operand types: string * float
847       $value = (float)mb_substr($l, 0, $i) * $root_font_size;
848        }
849
850        elseif (($i = mb_stripos($l, "em")) !== false) {
851            $value = (float)mb_substr($l, 0, $i) * $font_size;
852        }
```
I deduce that the types of units are not compatible to perform the multiplication. 
the error is canceled by adding (float)$font_size;
but is it the right solution?

Michel

**Comment by bsweeney** [comment] 2022-02-12 15:45
What is the rendering test? I'm unable to reproduce and am trying to understand what triggers the error.

**Comment by mipel85** [comment] 2022-02-13 09:13
Hi,
no rendering because this error is fatal but here is a screen of the type of graphics to print :
![Screenshot-garradin-Graphiques](https://user-images.githubusercontent.com/18450008/153746372-5ea88c48-8257-4bfa-942f-ce8226f21841.png)
and the result obtained: 
![Screenshot -dompdf-résult](https://user-images.githubusercontent.com/18450008/153746445-0b0edba7-5d26-4dab-992a-7a00f1d3704c.png)
I don't see how to help you more except that the unit conversions used in the css go wrong...
Michel

**Comment by MrTrick** [comment] 2022-02-14 09:22
> Is this something that's being encountered during rendering, or only with unit tests? I'm unable to reproduce while rendering a document, so if anyone has a sample that would be helpful.

@bsweeney it happens when I render a PDF receipt. (first encountered in my project's unit tests, but also happens in normal use)
It's an html file with embedded style sheet, with rules like:
```css
    table.totals td {
        border: 1px solid black;
        font-size: 15px;
        text-align: right;
        padding: 10px 40px 10px 10px;
    }
```

**Comment by bsweeney** [comment] 2022-02-14 14:37
@mipel85 I would like to see a sample of your HTML+CSS source not the rendered PDF. That way I can attempt to reproduce the error.

Thanks, @MrTrick, that's the type of info I was looking for. Still unable to reproduce, though. Could be a combination of different stylings that's causing the issue. Do you have a full sample that exhibits the issue?

**Comment by MrTrick** [comment] 2022-02-15 10:03
@bsweeney here's a script that triggers the error: 
[test_dompdf_1.2.0.php](https://gist.github.com/MrTrick/155b869a03714ca93c18ff38d03751b3#file-test_dompdf_1-2-0-php)
and the output: [test_dompdf_1.2.0_result.txt](https://gist.github.com/MrTrick/155b869a03714ca93c18ff38d03751b3#file-test_dompdf_1-2-0_result-txt)

Curiously, if you remove the `body {}` rule, you get a different set of errors reported: [test_dompdf_1.2.0_extra_result.txt](https://gist.github.com/MrTrick/155b869a03714ca93c18ff38d03751b3#file-test_dompdf_1-2-0_extra_result-txt)
🤔 maybe it's a separate issue?

**Comment by bsweeney** [comment] 2022-02-15 12:35
Thank you, that's it. Looks like specifying "inherit" on the HTML element is the cause.

```
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <style type="text/css">
            html {
                font: inherit;
            }
        </style>
    </head>
    <body>
        Nothing needed here.
    </body>
</html>
```

**Comment by mipel85** [comment] 2022-02-16 09:17
Hi,
Sorry but I am unable to provide more information due to lack of knowledge of the Garradin software that I have only been discovering for a few days.
If necessary : https://fossil.kd2.org/garradin/timeline

Michel

**Comment by mipel85** [comment] 2022-02-17 09:26
perfect, 
I'm looking forward to the fix so I can modify my plugin.
thanks in advance

**Comment by Mellthas** [comment] 2022-03-02 13:30
The test case provided by @bsweeney and similar cases using `inherit` on the root element should be fixed by #2790. Please let us know if the issue is still reproducible with the PR applied.

**Closed** 2022-03-04 09:10 UTC
Labels: bug, css

**Comment by mipel85** [comment] 2022-03-05 10:02
hello,
I just tested the commit and it's good for me.
When will these changes be incorporated into the latest release?

**Comment by DavidSprauel** [comment] 2022-03-21 11:03
Hello,
I've got this problem on my prod server for a client is there any quick fix I can do not to disturbe my client use ?

**Comment by mipel85** [comment] 2022-03-21 15:48
Hello,
You can update the library yourself from these commit: 
https://github.com/dompdf/dompdf/commit/9b05381fab25dfdadc62522fa99e78807a121138
just these 2 files to update and that will be enough.
Michel

**Comment by bsweeney** [comment] 2022-03-21 16:05
I hope to have a new release out this week, next for sure. In the meantime, if you want the latest code you can [use an alias in your composer configuration](https://getcomposer.org/doc/articles/aliases.md).
