### ISSUE TITLE
the table feet is larger than the page

### ISSUE THREAD

**Issue by romanown** [dompdf/dompdf#2097] opened 2020-02-24 14:07 UTC
when i printing the table it more then page. i tryed any version (from 0.6 to 0.8.4). layout need is portrait.
it is my html
```
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
</head>
<body>
  <table  border="1" cellpadding="2">
    <thead>
    <tr>
        <th width="20px">#</th>
        <th width="60px">Фото</th>
        <th width="120px">Предмет счета</th>
        <th width="70px">Штрих-код</th>
        <th width="40px">Кол-во</th>
        <th>Цена, руб.</th>
        <th>Скидка, руб.</th>
        <th>Сумма, руб.</th>
        <th width="70px">Ком-рий</th>
    </tr>
    </thead>
    <tbody>
           <tr>
            <td width="20px">1</td>
            <td width="60px"><img src="http://placehold.it/150x100" class="product-image"></td>
            <td width="120px" class="product-info">
                артикул:<br>
                размер: <br>
                бренд: <br>
                наименование: <br>
            </td>
            <td width="70px">
                        <img src="http://placehold.it/150x100" class="barcode">
            </td>
            <td width="40px">7</td>
            <td>56756</td>
            <td>89767</td>
            <td>6767</td>
            <td width="70px">орл ол олппо аппо попо поп</td>
        </tr>
    </tbody>
</table>
</body>
</html>
```

it is to `https://github.com/dompdf/dompdf/blob/master/src/FrameReflower/Text.php` line 413
`$words = array_flip(preg_split('/([^\S\xA0]+|-+)/u', $text, -1, PREG_SPLIT_DELIM_CAPTURE));`
i edited it to
`$words = array_flip(preg_split('/[^\S\xA0]+/u', $text, -1, PREG_SPLIT_DELIM_CAPTURE));`
and it worked for my.

**Comment by bsweeney** [comment] 2020-06-27 01:23
I'm unable to discern any significant different in rendering between 0.6 and 0.8.4 in the debug helper. Nor after making the suggested change locally. Is there any additional styling that could be affecting the render? Can you provide a version of the document rendered before the upgrade to 0.8.x?

The change you made should have the opposite affect, I would think, since you're removing one of the characters that is used to split a string into multiple lines.

**Comment by romanown** [comment] 2020-06-27 19:41
after the update, all the tables and images in these tables became wide. I have provided part of the code. to find the reason, I returned the old version back. in order not to waste a lot of time and not to think, I started replacing files one by one from the new version to the old one. after replacing the specified file, the result was bad. I compared the old and new versions of the files and started adding new ones. after adding the specified section, the result was bad. I completely updated the version in my North and deleted this section. the result was good. I wrote about it here. I priver an example of my file that I turn into a PDF. You can do this with different versions and find the reason. Since the result Is the same with both versions of the file, I suggest making my corrections. but I have solved my problem and if you think that these are useless amendments you can leave everything as it is. If others have a problem, let them solve it themselves. I don't insist, because I solved my problem by deleting Your change in my instance.

**Comment by romanown** [comment] 2020-06-27 19:42
since more than six months have passed, I have not saved the old versions of files. I'll look for them and if I find them I'll give them to You.

**Comment by romanown** [comment] 2020-06-27 22:05
here is a file that was formed incorrectly
[https://yadi.sk/i/JYo7eaAIxiHvbw](url)

**Comment by bsweeney** [comment] 2020-06-30 03:07
Thanks. That file may help determine the cause. If you can dig up the HTML that would be great but if not this should help build a sample.

[Товарный_чек_к_заказу_№9628.pdf](https://github.com/dompdf/dompdf/files/4849206/_._._._.9628.pdf)

**Comment by romanown** [comment] 2020-06-30 06:49
example
`<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
</head>
<body>
  <table  border="1" cellpadding="2">
    <thead>
    <tr>
        <th width="20px">#</th>
        <th width="60px">Фото</th>
        <th width="120px">Предмет счета</th>
        <th width="40px">Кол-во</th>
        <th>Цена, руб.</th>
        <th>Скидка, руб.</th>
        <th>Сумма, руб.</th>
        <th width="70px">Ком-рий</th>
        <th width="70px">Штрих-код</th>
    </tr>
    </thead>
    <tbody>
           <tr>
            <td width="20px">1</td>
            <td width="60px"><img src="http://placehold.it/150x100" class="product-image"></td>
            <td width="120px" class="product-info">
                артикул:<br>
                размер: <br>
                бренд: <br>
                наименование: <br>
            </td>
            <td width="40px">7</td>
            <td>56756</td>
            <td>89767</td>
            <td>6767</td>
            <td width="70px">орл ол олппо аппо попо поп</td>
            <td width="70px">
                        <img src="http://placehold.it/150x100" class="barcode">
            </td>
        </tr>
    </tbody>
</table>
</body>
</html>`

**Comment by romanown** [comment] 2020-06-30 06:54
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
</head>
<body>
  <table  border="1" cellpadding="2">
    <thead>
    <tr>
        <th width="20px">#</th>
        <th width="60px">Фото</th>
        <th width="120px">Предмет счета</th>
        <th width="40px">Кол-во</th>
        <th>Цена, руб.</th>
        <th>Скидка, руб.</th>
        <th>Сумма, руб.</th>
        <th width="70px">Ком-рий</th>
        <th width="70px">Штрих-код</th>
    </tr>
    </thead>
    <tbody>
           <tr>
            <td width="20px">1</td>
            <td width="60px"><img src="http://placehold.it/150x100" class="product-image"></td>
            <td width="120px" class="product-info">
                артикул: FMESOP30<br>
                размер: 40<br>
                бренд: Fermata <br>
                наименование: <br>
            </td>
            <td width="40px">1</td>
            <td>4550</td>
            <td>0</td>
            <td>4550</td>
            <td width="70px"></td>
            <td width="70px">
                        <img src="http://placehold.it/150x100" class="barcode">
            </td>
        </tr>
    </tbody>
</table>
</body>
</html>

**Comment by romanown** [comment] 2020-07-29 20:56
you may commit the my pullrequest to fix this issue?

**Comment by bsweeney** [comment] 2020-07-30 00:27
I have, up to now, been unable to reproduce the specific issue. Unless we can confirm that the change fixes an issue, and can ensure it does not have side effects that break rendering in other cases, we won't commit the PR.

Attached to this post is what I get when I render the sample HTML you posted earlier:

[issue2097-sample.pdf](https://github.com/dompdf/dompdf/files/4998115/issue2097-sample.pdf)

As you can see, it doesn't produce the output you noted with your original PDF. If you render that sample HTML do you see the issue?

**Comment by romanown** [comment] 2020-08-15 20:45
for me, this module started working correctly only after making the specified change. since other modules can't affect this, my change fixed the existing problem. I don't care if You make this change in your code or not. the main thing is that it works for me. if others do not work correctly, it will be their problem. let those who have the problem repeat will prove to you the need to fix it and let them look for the problem themselves. I'm tired of doing this and I don't want to continue to prove the usefulness of this change. this is your code and you decide whether to leave it in it or delete it. if I repeat this or another problem, I will not look for a solution, but will use another module, the creators of which will solve the problems, and not refuse to use the work I have done.

**Comment by bsweeney** [comment] 2020-08-19 21:41
I'm not refusing your work, I'm asking for your help in confirming the problem. If you feel you have done enough that's perfectly acceptable. You have no obligation to do more. However, we also won't accept the change you've suggested without confirming the underlying issue and the viability of the change. The obligation of the Dompdf developers is to the entire community of users and this level of validation is intended to ensure stability in the code.

So, please, help us help you. Or not. I'll continue to review the issue with or without any further input from you.

---

Since you argue that your change is an obvious good and that I'm being unreasonable for not accepting it I spent a bit more time analyzing it. After all, I'm not unreasonable. A change without confirmation of an underlying issue is acceptable so long as the change is an obvious good.

In reviewing your pull request what I see is that your change is not an obvious good. Modifying the word break logic for min/max width calculation without modifying the actual word break logic can create a situation where the minimum text width calculation does not match the actual text width when split into multiple lines. You can see this in the following two example renders:

Sample HTML:

```
<table border="1" width="5em">
  <tr>
    <td>
      dompdf-rendered
    </td>
    <td>
      dompdf-rendered
    </td>
  </tr>
</table>
```

Master | PR2102
------ | ------
![master](https://user-images.githubusercontent.com/485897/90691947-3699f600-e242-11ea-88a3-4995c860621b.png) | ![pr2102](https://user-images.githubusercontent.com/485897/90691980-4a455c80-e242-11ea-9466-eb29c5f3d589.png)

As you can see, removing the dash from the width calculation results in the Dompdf thinking the text is wider than it actually is, and a table cell wider than it needs to be. Based on this further review it seems likely that the change you suggest will only exacerbate the issue you are trying to address.

---

I can't deny it would appear to you that the change you made addresses the issue on your own system. Dompdf is complex and so it's easy to cause unintended consequences when trying to modify the code. I welcome further input from you on the underlying issue, if you're willing to provide it, so that a solution that works for everybody can be found.

**Comment by bsweeney** [comment] 2022-12-29 19:01
We've implemented significant changes to the layout logic since 0.8.x. Closing now, but feel free to post back if the issue is still present in the most recent release.

**Closed by bsweeney** 2022-12-29 19:01 UTC
Labels: question
