### ISSUE TITLE
Overlapping Table Rows After First Page

### ISSUE THREAD

**Issue by mitchelltaylor159** [dompdf/dompdf#1832] opened 2018-10-31 18:59 UTC
I am trying to generate a PDF to print labels on 30-labels-per-sheet paper:

![](http://www.labeloutfitters.com/assets/images/258100-Dimensions.jpg)

After a bit of playing to get the dimensions of the labels to render correctly, I did a test with multiple pages of labels.  On each page after the first, the first and second rows overlap (unless I insert a blank page before the first page, in which case they all render correctly - but that isn't really a professional solution). Note: My table does not flow over multiple pages, because I chose to use a separate `div` for each sheet to better handle page-breaking.

Is this an issue with DomPDF or is there something I can to do make this work?

__My (Relevant) CSS:__

```
@page {
  margin: 0;
}

.page {
  page-break-inside: avoid;
}

.page:nth-child(n+1) {
  page-break-before: always;
}

* {
  box-sizing: border-box;
}

table {
  border-collapse: collapse;
}

table td, table th {
  border: none;
}

.text-left {
  text-align: left;
}

.text-center {
  text-align: center;
}

.text-right {
  text-align: right;
}

.text-top {
  vertical-align: top;
}

.text-middle {
  vertical-align: middle;
}

.text-bottom {
  vertical-align: bottom;
}

.text-80 {
  font-size: 0.8rem;
}

.text-90 {
  font-size: 0.9rem;
}

.text-small {
  font-size: 0.7rem;
}

table.t5160 {
  width: 8.5in;
  border: none;
  border-collapse: collapse;
}

table.t5160 td {
  border: none;
  text-align: center;
  vertical-align: middle;
}

table.t5160 tr.margin-top {
  height: 0.45714in;
}

table.t5160 tr.margin-top td {
  height: 0.45714in;
}

table.t5160 tr.margin-bottom td {
  height: 0.47656in;
}

table.t5160 tr.label-row {
  height: 0.9697in;
}

table.t5160 tr.label-row td {
  height: 0.9697in;
}

table.t5160 td.margin-left, table.t5160 td.margin-right {
  width: 0.2in;
}

table.t5160 td.label {
  width: 2.47753in;
}

table.t5160 td.margin-inner {
  width: 0.125in;
}
```

__My HTML (Validated XHTML using ![validator.w3.org](validator.w3.org) ):__
(Dynamically Generated, but changed all words to "label")

```
<!doctype html>
<html>

<head>
    <title>document</title>
    <link rel="stylesheet" href="http://192.168.56.101/v1/src/Resources/CSS/documents.css">
</head>

<body>
    <div class="page">
        <table class="t5160">
            <tbody>
                <tr class="margin-top">
                    <td colspan="7" class="margin-top"></td>
                </tr>
                <tr class="label-row">
                    <td class="margin-left">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span>Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-inner">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span class="text-90">Label<br></span><span class="text-80">Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-inner">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span>Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-right">&nbsp;</td>
                </tr>
                <tr class="label-row">
                    <td class="margin-left">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span class="text-90">Label<br></span><span class="text-80">Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-inner">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span>Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-inner">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span class="text-90">Label<br></span><span class="text-80">Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-right">&nbsp;</td>
                </tr>
                <tr class="label-row">
                    <td class="margin-left">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span>Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-inner">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span class="text-90">Label<br></span><span class="text-80">Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-inner">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span>Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-right">&nbsp;</td>
                </tr>
                <tr class="label-row">
                    <td class="margin-left">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span class="text-90">Label<br></span><span class="text-80">Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-inner">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span>Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-inner">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span class="text-90">Label<br></span><span class="text-80">Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-right">&nbsp;</td>
                </tr>
                <tr class="label-row">
                    <td class="margin-left">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span>Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-inner">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span class="text-90">Label<br></span><span class="text-80">Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-inner">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span>Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-right">&nbsp;</td>
                </tr>
                <tr class="label-row">
                    <td class="margin-left">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span class="text-90">Label<br></span><span class="text-80">Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-inner">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span>Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-inner">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span class="text-90">Label<br></span><span class="text-80">Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-right">&nbsp;</td>
                </tr>
                <tr class="label-row">
                    <td class="margin-left">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span>Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-inner">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span class="text-90">Label<br></span><span class="text-80">Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-inner">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span>Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-right">&nbsp;</td>
                </tr>
                <tr class="label-row">
                    <td class="margin-left">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span class="text-90">Label<br></span><span class="text-80">Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-inner">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span>Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-inner">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span class="text-90">Label<br></span><span class="text-80">Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-right">&nbsp;</td>
                </tr>
                <tr class="label-row">
                    <td class="margin-left">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span>Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-inner">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span class="text-90">Label<br></span><span class="text-80">Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-inner">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span>Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-right">&nbsp;</td>
                </tr>
                <tr class="label-row">
                    <td class="margin-left">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span class="text-90">Label<br></span><span class="text-80">Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-inner">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span>Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-inner">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span class="text-90">Label<br></span><span class="text-80">Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-right">&nbsp;</td>
                </tr>
            </tbody>
        </table>
    </div>
    <div class="page">
        <table class="t5160">
            <tbody>
                <tr class="margin-top">
                    <td colspan="7" class="margin-top"></td>
                </tr>
                <tr class="label-row">
                    <td class="margin-left">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span>Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-inner">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span class="text-90">Label<br></span><span class="text-80">Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-inner">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span>Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-right">&nbsp;</td>
                </tr>
                <tr class="label-row">
                    <td class="margin-left">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span class="text-90">Label<br></span><span class="text-80">Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-inner">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span>Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-inner">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span class="text-90">Label<br></span><span class="text-80">Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-right">&nbsp;</td>
                </tr>
                <tr class="label-row">
                    <td class="margin-left">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span>Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-inner">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span class="text-90">Label<br></span><span class="text-80">Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-inner">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span>Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-right">&nbsp;</td>
                </tr>
                <tr class="label-row">
                    <td class="margin-left">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span class="text-90">Label<br></span><span class="text-80">Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-inner">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span>Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-inner">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span class="text-90">Label<br></span><span class="text-80">Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-right">&nbsp;</td>
                </tr>
                <tr class="label-row">
                    <td class="margin-left">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span>Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-inner">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span class="text-90">Label<br></span><span class="text-80">Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-inner">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span>Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-right">&nbsp;</td>
                </tr>
                <tr class="label-row">
                    <td class="margin-left">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span class="text-90">Label<br></span><span class="text-80">Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-inner">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span>Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-inner">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span class="text-90">Label<br></span><span class="text-80">Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-right">&nbsp;</td>
                </tr>
                <tr class="label-row">
                    <td class="margin-left">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span>Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-inner">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span class="text-90">Label<br></span><span class="text-80">Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-inner">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span>Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-right">&nbsp;</td>
                </tr>
                <tr class="label-row">
                    <td class="margin-left">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span class="text-90">Label<br></span><span class="text-80">Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-inner">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span>Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-inner">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span class="text-90">Label<br></span><span class="text-80">Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-right">&nbsp;</td>
                </tr>
                <tr class="label-row">
                    <td class="margin-left">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span>Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-inner">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span class="text-90">Label<br></span><span class="text-80">Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-inner">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span>Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-right">&nbsp;</td>
                </tr>
                <tr class="label-row">
                    <td class="margin-left">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span class="text-90">Label<br></span><span class="text-80">Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-inner">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span>Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-inner">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span class="text-90">Label<br></span><span class="text-80">Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-right">&nbsp;</td>
                </tr>
            </tbody>
        </table>
    </div>
    <div class="page">
        <table class="t5160">
            <tbody>
                <tr class="margin-top">
                    <td colspan="7" class="margin-top"></td>
                </tr>
                <tr class="label-row">
                    <td class="margin-left">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span>Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-inner">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span class="text-90">Label<br></span><span class="text-80">Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-inner">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span>Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-right">&nbsp;</td>
                </tr>
                <tr class="label-row">
                    <td class="margin-left">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span class="text-90">Label<br></span><span class="text-80">Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-inner">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span>Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-inner">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span class="text-90">Label<br></span><span class="text-80">Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-right">&nbsp;</td>
                </tr>
                <tr class="label-row">
                    <td class="margin-left">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span>Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-inner">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span class="text-90">Label<br></span><span class="text-80">Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-inner">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span>Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-right">&nbsp;</td>
                </tr>
                <tr class="label-row">
                    <td class="margin-left">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span class="text-90">Label<br></span><span class="text-80">Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-inner">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span>Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-inner">&nbsp;</td>
                    <td class="label">
                        <div>
                            <div><b>Label</b>
                                <br>
                            </div><span class="text-90">Label<br></span><span class="text-80">Label</span><span><br>Label</span></div>
                    </td>
                    <td class="margin-right">&nbsp;</td>
                </tr>
            </tbody>
        </table>
    </div>
</body>

</html>
```

__The Result (See the top rows of pages 2 and 3):__
[labels.pdf](https://github.com/dompdf/dompdf/files/2535876/labels.pdf)

__If I tell it to page-break before the first page, it formats correctly:__
[labels(1).pdf](https://github.com/dompdf/dompdf/files/2535906/labels.1.pdf)

**Comment by bsweeney** [comment] 2018-11-13 03:29
This seems to be an issue. We'll need to take a closer look to see what's going on.

**Comment by ThomasLandauer** [comment] 2019-06-17 18:59
I couldn't reproduce @mitchelltaylor159 's example in dompdf 0.8.3.

However, I have another, which might be related ;-) 

```php
$tr = '';
for ($i=1; $i<=200; $i++)
{
    $tr .= '<tr><td><span class="box">'.$i.'</span></td></tr>';
}

$html = <<<EOD
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <style>
            .box { display:inline-block; width:2rem; height:1rem; border:1px solid black; }
        </style>
    </head>
    <body>
        <table>
            $tr
        </table>
    </body>
</html>
EOD;

$dompdf = new Dompdf();
$dompdf->loadHtml($html);
$dompdf->setPaper('A4', 'portrait');
$dompdf->render();
$dompdf->stream('foo.pdf');
```

Result: The first page is ok. But starting from the second page, in the first line (i.e. the first `td` on the page) the number is rendered to the right of the box (instead of inside). So of my 200 boxes, 196 are ok; the problem occurs in the boxes number 47, 92, 137, and 182.

Some more observations:
* Adding a blank page in the beginning (as @mitchelltaylor159 suggested) didn't change anything. When I add an element with `page-break-before:always;` (or `page-break-after:always;`) I do get the blank page, but the problem still starts on the second page of the table (i.e. page 3 in total).
* If I add a `height` to `.box`, the number gets moved upwards too. So it looks like the width/height of the box is somehow being misinterpreted to position the containing content *after* the box.
* `display:inline-block;` seems to be crucial - if I change it to `block`, the problem disappears.

**Comment by bsweeney** [comment] 2019-06-18 00:08
Thanks, @ThomasLandauer. Definitely seeing that!

**Comment by Mellthas** [comment] 2021-09-15 21:45
I can't reproduce the first issue with 1.0.2, too, so it seems to be fine now. The second issue should be addressed by #2548.

**Closed** 2021-09-17 16:58 UTC

**Comment by jds1993cologne** [comment] 2021-09-24 12:46
I had a reproduce with 1.0.2

**Comment by bsweeney** [comment] 2021-09-24 13:58
@jds1993cologne the 1.1.0 release should address the issue. Have you tried with the develop branch (dev-develop in composer) or the [nightly download](http://eclecticgeek.com/dompdf/dompdf_nightly.zip)?

**Comment by Nico-Schaefer-2111** [comment] 2023-01-19 12:11
Is there a workaround for version 1.0.2

**Comment by bsweeney** [comment] 2023-01-19 13:06
I am unaware of a work around. Recommend upgrading to the latest release if you can.

**Comment by Nico-Schaefer-2111** [comment] 2023-01-19 13:35
@bsweeney one can only try to display the elements as table cols, if the elements should be displayed horizontically
