### ISSUE TITLE
DOMPDF not formatting PDF output properly on live server

### ISSUE THREAD

**Issue by yankitwizzy** [dompdf/dompdf#731] opened 2013-10-24 18:08 UTC
I have a script that generates a pdf file using DOMPDF. Locally it generates fine the way I want it to be but online, the formatting is scattered. These are the two samples. The first is the output on localhost while the 2nd is the output on the live server
![well formated on localhost](https://f.cloud.github.com/assets/1004830/1401489/f3998e64-3cd6-11e3-93ba-52da4f7e7a1d.jpg)
![not well formated](https://f.cloud.github.com/assets/1004830/1401494/19586bde-3cd7-11e3-936b-703dc19d1347.jpg)
On both localhost and live server, I am using PHP 5.3.x. Please what could be the problem. I am using the latest version of dompdf

**Comment by gerbengeeraerts** [comment] 2016-10-04 14:31
Same problem here, this bug is still relevant and present.

**Comment by gerbengeeraerts** [comment] 2016-10-04 14:33
![knipsel](https://cloud.githubusercontent.com/assets/329409/19078390/3d659ae6-8a50-11e6-804a-99827aa80ebb.PNG)
![knipsel2](https://cloud.githubusercontent.com/assets/329409/19078391/3d7afe90-8a50-11e6-8746-03de10e7cb62.PNG)

**Comment by bsweeney** [comment] 2016-10-04 16:52
@gerbengeeraerts hard to tell without looking at the HTML, but your issue looks more to be a problem with the font metrics. Have you tried resetting to the distribution default the dompdf font and font cache directories (default is dompdf/lib/fonts).

**Comment by gerbengeeraerts** [comment] 2016-10-07 11:39
I've added the "$dompdf->set_option('defaultFont', 'Arial');" option, but that didn't change anything.
I could post my html if that would be interesting. It's not that much.
It contains no floats and is all tables.

**Comment by bsweeney** [comment] 2016-10-08 04:16
Would certainly help to see the HTML.

**Comment by MayconGhizzi** [comment] 2016-10-24 14:11
I recently solve this problem, check server required extensions:

PHP version 5.3.0 or higher
DOM extension
GD extension
MBString extension
php-font-lib
php-svg-lib

in my case MbString was missing.

**Comment by bsweeney** [comment] 2016-10-24 14:16
Ah, yes. that would do it. In 0.6.2 we had a replacement library for installations where MBString was missing. With 0.7.0 we decided to make it a requirement instead. Not sure at this point if we'll provide a fallback in the future.

Maybe we'll look to add an initialization routine that checks for required libraries.

**Comment by sj5515139** [comment] 2017-03-31 07:27
I am using dompdf for generating pdf in Drupal 7. its working very fine on localhost. But its not working on online server. There it is not generating page also. It just reload the page again. Anybody please help me.

**Comment by bsweeney** [comment] 2017-04-11 22:55
@sj5515139 you might want to head over to [StackOverflow](http://stackoverflow.com/questions/tagged/dompdf) or
the [Google Groups](http://groups.google.com/group/dompdf) to talk through what's going on.

**Comment by avadh22** [comment] 2018-04-05 13:39
some dompdf file not download why?

**Comment by bsweeney** [comment] 2018-04-08 15:41
@avadh22 please [start a new issue](https://github.com/dompdf/dompdf/issues/new) and provide more detail. Or, if you're not sure what the problem is please start a discussion on the [support forum](https://groups.google.com/forum/#!forum/dompdf).

**Comment by dev-pradeep** [comment] 2018-11-16 14:05
Anyone figured the solution this issue ? as its same for me in locally its working like a charm but in live its all messed up

**Comment by ronaldaraujo** [comment] 2019-07-02 20:15
There are two possibilities:
1. The absolute path of CSS is wrong;
2. The CSS file inside the server is read-protected.

**Comment by JCBabu** [comment] 2019-10-24 21:20
> Did you download the archive from github? If so you'll be missing php-font-lib. Try downloading a "nightly" from here: http://eclecticgeek.com/dompdf

It works. tnks so muchs.. i spend to much time finding a solution.

**Comment by mayanksdudakiya** [comment] 2019-12-30 18:11
> 
> 
> Did you download the archive from github? If so you'll be missing php-font-lib. Try downloading a "nightly" from here: http://eclecticgeek.com/dompdf

Yes, This too  work for me. Thanks a lot. :)

**Comment by bsweeney** [comment] 2020-01-23 02:52
Don't know that we'll get around to that checkup script anytime soon but this issue has served it's purpose so I'm going to go ahead and close it.

**Closed by bsweeney** 2020-01-23 02:52 UTC
Labels: On Deck, enhancement

**Comment by Expertweblancer** [comment] 2020-09-22 17:42
![image](https://user-images.githubusercontent.com/40166803/93917792-0cb87100-fcd1-11ea-9ffc-47d16ab13817.png)

**Comment by Expertweblancer** [comment] 2020-09-22 17:42
![image](https://user-images.githubusercontent.com/40166803/93917820-16da6f80-fcd1-11ea-8b59-04b9c9586976.png)

**Comment by Expertweblancer** [comment] 2020-09-22 17:44
I am using DomPDF in Laravel project. It works well but there is one problem.
I used the custom font and if I download the PDF, it shows properly
But I save the PDF file into the public directory, it doest show properly. 
I am not sure what the problem is.

**Comment by TheGranthiq** [comment] 2020-09-23 23:49
Same Problem...
if you have any solution so far, then let me know

**Comment by bsweeney** [comment] 2020-09-24 15:10
Seems like a different problem, suggest you open a new issue with details about how you're saving to public and accessing from there.

**Comment by monarksoni** [comment] 2021-04-16 17:32
I have an html page that generates a pdf file using DOMPDF. Locally it generates fine the way I want it to be but online, the formatting is scattered. These are the two samples. The first is the output on the HTML Page look like
![Screenshot 2021-04-16 at 10 57 53 PM](https://user-images.githubusercontent.com/61448928/115061759-305e3580-9f07-11eb-9ac5-ebbed5c5bb73.png)

while the 2nd is the output on the PDF look different
![Screenshot 2021-04-16 at 10 58 28 PM](https://user-images.githubusercontent.com/61448928/115061832-453ac900-9f07-11eb-8e45-a0fc22f6308d.png)

**Comment by andrew21-mch** [comment] 2023-10-19 15:14
> I have an HTML page that generates a pdf file using DOMPDF. In the HTML page, it generates fine the way I want it to be but in PDF, the formatting is scattered. These are the two samples. The first is the output on the HTML Page look like ![Screenshot 2021-04-16 at 10 57 53 PM](https://user-images.githubusercontent.com/61448928/115061759-305e3580-9f07-11eb-9ac5-ebbed5c5bb73.png)
> 
> while the 2nd is the output on the PDF look different ![Screenshot 2021-04-16 at 10 58 28 PM](https://user-images.githubusercontent.com/61448928/115061832-453ac900-9f07-11eb-8e45-a0fc22f6308d.png)

please did you find a fix to this @monarksoni
