### ISSUE TITLE
dompdf and drupal entity_print

### ISSUE THREAD

**Issue by code137** [dompdf/dompdf#2244] opened 2020-09-18 15:56 UTC
Not exactly sure if there's an issue with dompdf, drupal, or the drupal entity_print module but was running into issue where pdf generation was returning network errors and failing to load. Tracing it through I could see that 'none' would be upgraded to 'url(none)' and then translated in Style.php to create urls like http://localhostnone or <domain>none which would then fail to load correctly throwing a network error. I was able to resolve it locally by adding another catch. Any thoughts on whether this is something worth catching in Style or if it's just a symptom of an issue further up in the data passed to dompdf?

```diff --git a/src/Css/Style.php b/src/Css/Style.php
index e2fc6c1..e184fab 100644
--- a/src/Css/Style.php
+++ b/src/Css/Style.php
@@ -1804,7 +1804,7 @@ class Style
         $DEBUGCSS = $this->_stylesheet->get_dompdf()->getOptions()->getDebugCss();
         $parsed_url = "none";
 
-        if (empty($val) || $val === "none") {
+        if (empty($val) || $val === "none" || $val === "url(none)") {
             $path = "none";
         } else if (mb_strpos($val, "url") === false) {
             $path = "none"; //Don't resolve no image -> otherwise would prefix path and no longer recognize as none
```

**Comment by bsweeney** [comment] 2020-09-19 03:55
The modification of the property from "none" to "url(none)" sounds like an issue with your drupal module. But if this is an issue with Dompdf it should be easy to identify.

I'm not sure if we want to do that level of URL parsing but it's something to think about since it's an obvious error. In the meantime, since you're able to do that level of tracing, can you confirm the source of the property transformation? Easiest way to tell if it's Dompdf is to look at the HTML passed to Dompdf.

**Comment by luigimannoni** [comment] 2020-10-14 10:58
Same started happening on our Drupal site recently, my colleague rolled back dompdf to 0.8.5 and it started working again and file_get_contents gets the images properly

**Comment by ytsurk** [comment] 2020-10-16 14:56
I can confirm that this changes makes the Drupal module work again.

And it is not related to Drupal, nor dompdf, but non-valid CSS.

The call-stack comes from 

```php
  /**
   * Returns the background image URI, or "none"
   *
   * @link https://www.w3.org/TR/CSS21/colors.html#propdef-background-image
   * @return string
   */
   function get_background_image()
   {
      return $this->_image($this->_props_computed["background_image"]);
   }
```

and the the CSS background image property **url(none)** is widly used - but not exactly valid, see fe. https://stackoverflow.com/questions/1161061/css-background-image-urlnone-leading-to-errors-in-apache-log-file

Maybe the mentioned method should be adapted to transform url(none) and to none, like
```php
  /**
   * Returns the background image URI, or "none"
   *
   * @link https://www.w3.org/TR/CSS21/colors.html#propdef-background-image
   * @return string
   */
   function get_background_image()
   {
     $tmp = $this->_props_computed["background_image"];
     if ($tmp == 'url(none)') {
       // url(none) is not a valid CSS value for background-image, but widely used.
       $tmp = 'none';
     }
     return $this->_image($tmp);
   }
```

**Comment by bsweeney** [comment] 2020-10-16 18:28
I'll have to consider the implications of the suggested change. Unlikely that someone would have a resource named "none" but also not entirely impossible. Rather than building in a workaround to non-standard CSS it may be possible to avoid the error that's generated when attempting to access the "none" resource. I'll have to work through the code flow to see what's happening.

Just noting the error for reference:
> Error generating document: Failed to generate PDF: file_get_contents(): php_network_getaddresses: getaddrinfo failed: Name or service not known

**Comment by bsweeney** [comment] 2020-11-13 15:23
Question for everyone, is Drupal setting a base href on your documents and, if so, do the invalid requests continue if you remove the base href?

**Comment by ytsurk** [comment] 2020-11-13 15:37
It depends on the theme/setup/customization used. But the shipped and most popular themes do not set a 

`<base href=""/>` in `<head>`

**Comment by luigimannoni** [comment] 2020-11-13 15:47
There's no base href in our theme, nor we do enforce a base URL on Drupal's settings.

However I can confirm that `file_get_contents()` tries an URL similar to `https://www.example.com/none`

**Comment by bsweeney** [comment] 2020-11-13 15:55
I should have thought that question through a bit more. I'm working on a fix to an issue with CSS image-url parsing where "none" is being re-interpreted as "{base_href}none" so a few factors come into play such as whether the document has a base href, how the document is loaded into dompdf, whether the stylesheet is embedded in the document or external.

This seems like the most probable cause of the issue if this is a problem that started with 0.8.6 and drupal itself isn't generating the invalid reference.

**Comment by luigimannoni** [comment] 2020-11-14 21:14
Sorry, should've expanded my answer a little bit more and probably this will point you to the right direction. (I am not with my laptop now so take the with a pinch of salt)

We run the site on docker containers, website is served from a nginx container while the php code runs somewhere else in a different container.

The php container has to query the full URL to get the images from Drupal so I do assume it is ultimately parsing with a base href somewhere, however where is it set it is beyond me.
We do have a Drupal multisite installation if that helps!

**Comment by ytsurk** [comment] 2020-11-16 09:38
@luigimannoni Changing the base_url (or maybe even it's protocol to file://, this is what I do for dockerized Drupal instances) is not related to this HTML property and is addressed in the issue #2098.

**Comment by ytsurk** [comment] 2020-11-23 08:24
@bsweeney - The patch works great, and fixes the use with the images paths (also for list-style).

Thank you.

**Comment by NelsNose** [comment] 2020-11-28 01:47
Forgive me if I've misunderstood, but line 1814 (after applying this as a patch), I believe 
`} else if (mb_strpos($val, "url") === false) {`
should be 
`} else if (mb_strpos($val, "url") == false) {`

As the case of "url(none)" will return 0 instead of false, so the strict check will never catch the case.

**Comment by ytsurk** [comment] 2020-11-28 19:21
Good catch, this is definitely the case.
`url(none)` is be handled correctly by the else {} case, but should never go there!

**Comment by bsweeney** [comment] 2020-11-29 20:28
The change I made wasn't an attempt to address parsing a CSS URL with a value of `url(none)`. The issue I wanted to address was the fact that Dompdf itself was generating that value when parsing the CSS. I generally prefer to avoid adding non-standard parsing logic where possible. Since the actual source of that value was Dompdf and not drupal (afaik) I don't know that it's worth it to add an exception to parse this invalid CSS.

**Comment by bsweeney** [comment] 2020-12-13 14:44
I consider the issue closed since the source of the problem reported by OP was Dompdf itself. If anyone wants to further discuss the handling of "url(none)" please open a separate issue. As of now I'm not convinced Dompdf needs to handle this case since current handling is per the standard and consistent with web browsers.

**Closed by bsweeney** 2020-12-13 14:44 UTC
Labels: bug, css
