### ISSUE TITLE
CSS background image doesn't work with relative paths since 0.8.6

### ISSUE THREAD

**Issue by daniser** [dompdf/dompdf#2241] opened 2020-09-16 11:45 UTC
Given the next PHP and HTML code:
```
<?php

$options = new Dompdf\Options;
$options->setIsHtml5ParserEnabled(true);
$options->setIsRemoteEnabled(true);

$dompdf = new Dompdf\Dompdf($options);

$dompdf->loadHtml(<<<'HTML'
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>Background test</title>
        <link rel="stylesheet" type="text/css" href="<my host>/media/test/test.css" />
    </head>
    <body>
        <div class="test">This text must have background.</div>
    </body>
</html>
HTML
);

$dompdf->setPaper('A4', 'PORTRAIT');
$dompdf->render();

$dompdf->stream('test.pdf', ['Attachment' => false]);

exit;
```
and following CSS (/media/test/test.css + test.png in the same folder):
```
.test {
    padding: 10px;
    background-image: url(/media/test/test.png); /* or just "test.png"; fully qualified URI works */
}
```
It results in no background in 0.8.6 version of Dompdf.

**Comment by bsweeney** [comment] 2020-09-16 13:56
This may be due to an update to a new security restriction added to 0.8.6. Local resources are now restricted to those under the directory specified in the chroot option. Please review #2229 and let us know if you need additional help.

**Comment by daniser** [comment] 2020-09-16 17:56
Thanks, it worked!
But I still need to remove leading slash in PNG path in order to make it work:
`background-image: url(media/test/test.png);` <- works with chroot
`background-image: url(/media/test/test.png);` <- doesn't work

**Comment by PDFCoder** [comment] 2020-09-25 11:05
I confirm the problem. At least if the image is located in the same directory as the css file the url without any path should work correctly.

We also have the problem with relative paths, e.g. url(../images/test.png). With 0.8.6 relative paths in a css file won't work, even with chroot option set to "/". Will these work again in the upcoming 0.8.7 with the extended chroot option of PR #2232 ?

**Comment by PDFCoder** [comment] 2020-09-28 14:55
After some testing we found out that the code change according to #2215, "Use document base HREF for document-local CSS" (commit 32e85f8), is causing the problem (at least in our test scenario). If I comment out these changes the background images are shown correctly.

**Comment by bsweeney** [comment] 2020-09-28 16:39
@PDFCoder thank you for the update. I'll review that change in more details based on the information here and make any required updates. It would help if you can provide a fuller example of the issue, including:
- relevant PHP used to load/render the document
- the HTML + CSS
- any external stylesheet files involved

**Comment by PDFCoder** [comment] 2020-09-29 10:58
Our html/css is similar to the code @daniser already posted. For example we use background images for pretty designed bullet lists (ul li).

I think the problem might be the directory/file structure – for this to work with 0.8.6 we also have to set chroot option to "/":

– root with php file using dompdf
|– css: css file, ul li {background: url(../images/bullet.png) no-repeat;}
|– images: image file (bullet.png)

All files are located on the local webspace, no external stylesheets or images loaded via http. 

But it also makes no difference, if the image file is placed in the css folder (ul li {background: url(bullet.png) no-repeat;}). This also doesn't work. As @daniser mentioned above.

**Comment by bsweeney** [comment] 2020-09-29 12:54
Thank you for the follow up. I believe I tested that scenario but I'll have to double check. If the CSS is external to the file then Dompdf should be using the base href of the CSS document.

**Comment by bsweeney** [comment] 2020-12-17 16:36
OK, yeah, I see what's going on. Because there is a single Stylesheet instance, as the base href for the stylesheet changes it impacts how URLs are interpreted. For your particular use case, even if you reverse the change you pointed out an external stylesheet followed by a document stylesheet has the same affect.

```
<link rel="stylesheet" type="text/css" href="<my host>/media/test/test.css" />
<style>
   div { margin: 1em; }
</style>
```

I think, ideally, we would have a separate Stylesheet instances for each discreet base. That'll require a bit more work to implement.

In the meantime, this particular issue appears to be caused by the fact that when styles from various sources are merged we're doing so using the original, specified value. This computes a new value in the context of the current base href for the stylesheet. Trying to determine how best to address that, but will probably end up doing a straight copy if the computed value has already been specified.

**Closed** 2020-12-17 17:35 UTC
Labels: bug, css
