### ISSUE TITLE
text-align: justify - not rendered properly

### ISSUE THREAD

**Issue by at2software** [dompdf/dompdf#3343] opened 2023-12-05 09:53 UTC
I am using DomPDF with [these wrapper for Laravel](https://github.com/barryvdh/laravel-dompdf).
In some random lines, the css attribute `text-align: justify` doesn't seem to render properly.
The affected Lines don't line up with the other lines on the right side.
The text is inside the same paragraph-tag and i'm using b-, i-, and span-tags for formatting.

**Comment by bsweeney** [comment] 2023-12-05 15:26
We would need to see the HTML that's not being rendered correctly. Also, which version of the library are you using?

**Comment by at2software** [comment] 2023-12-06 08:34
Here is a HTML-Snippet, where the error occures:

```html
<p style="text-align: justify; text-justify: inter-word; text-align-last: left; line-height: 1.5;">
	Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore
	magna aliquyam erat, <span style="color:rgb(239, 126, 5)">sed diam voluptua</span>. At vero eos et accusam et justo duo dolores et
	ea <b>rebum</b>. Stet clita kasd gubergren, no sea takimata <b>sanctus</b> est <b>Lorem ipsum</b> dolor sit amet.
	<i>Lorem ipsum</i> dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et
	dolore magna aliquyam erat, sed diam voluptua.<br />
	<span style="color:rgb(27, 80, 147)">Lorem ipsum</span> dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore
	magna aliquyam erat, <b>sed diam</b> <span style="color:rgb(27, 80, 147)">voluptua</span>. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd
	gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem <b>ipsum dolor</b> sit amet, consetetur sadipscing
	elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero
	eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum
	dolor sit amet. Lorem ipsum dolor sit amet, <span style="color:rgb(27, 80, 147)">consetetur sadipscing</span> elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore
	magna <i>aliquyam erat</i>, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd
	gubergren, no sea <b>takimata</b> sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing
	elitr, sed diam nonumy eirmod tempor invidunt ut <span style="color:rgb(166, 24, 44)">labore et dolore magna aliquyam erat, sed diam voluptua. At vero</span>
	eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum
	dolor sit amet.<br />
	Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore
	magna aliquyam erat, <span style="color:rgb(239, 126, 5)">sed diam voluptua</span>. At vero eos et accusam et justo duo dolores et
	ea <b>rebum</b>. Stet clita kasd gubergren, no sea takimata <b>sanctus</b> est <b>Lorem ipsum</b> dolor sit amet.
	<i>Lorem ipsum</i> dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et
	dolore magna aliquyam erat, sed diam voluptua.
</p>
```

Here is a Picture showing the different offsets:

![text-align](https://github.com/dompdf/dompdf/assets/8616861/53d1080a-5ed2-4317-9fc4-c15e969608c7)

I`m using laravel-dompdf v2.0.1, which seems to use dompdf v2.0.1.

**Comment by bsweeney** [comment] 2023-12-07 17:16
This looks to be a duplicate of #547 so follow that ticket for updates.

**Closed by bsweeney** 2023-12-07 17:16 UTC
Labels: duplicate
