### ISSUE TITLE
error Cellmap

### ISSUE THREAD

**Issue by idairaaleman** [dompdf/dompdf#1129] opened 2016-02-28 15:01 UTC
hi,i have the next problem;

Fatal error: Call to undefined method DOMText::getAttribute() in /home/tonotour/public_html/dompdf/src/Cellmap.php on line 555

the line 555 is $colspan = $node->getAttribute("colspan");

what's happen?

**Comment by bsweeney** [comment] 2016-02-29 03:09
Difficult to say without seeing a sample of the HTML. However, as a first shot I'd say run your HTML through a validator. Errors like this typically show up when there are structural issues with the document that dompdf is unable to handle. You also might try enabling the HTML5 parser.

**Comment by idairaaleman** [comment] 2016-02-29 17:39
hi! this is my html;

<patTemplate:tmpl name="pageoutput" unusedvars="strip">
<style>
he i have my style
</style>

<div class="container">

<table width="100%" class="table table-striped table-bordered table-condensed" sTYLE="table-layout:fixed">
		<thead>
			<tr>
				<td colspan="4"><center><img src="/images/logohead.png" WIDTH=240 HEIGHT=126 ALT="logo empresa"><br>
				<center>TONOTOUR ESTANCIAS VACACIONALES,S.L<br>
				Teléfono: 922xxxxxxx.</center></td>
				<td colspan="5">{CLIENT_DETAILS_TEMPLATE}</td>			
				
			</tr>

			<tr>
				<th colspan="4">{HINVOICENO}: {ID}</th>
				<th colspan="3"><fon size=1>{HRAISED}: {RAISED}</fon></th>
				<th> {_JOMRES_BOOKING_NUMBER}: {BOOKING_NUMBER}</th>
			</tr>
			<tr>
				<th colspan="9">{BUSINESS_DETAILS_TEMPLATE}</th>
			</tr>				

			<tr>
				<th colspan="3" width="10%"><font size=1>{HLI_NAME}</font></th>
				<th><font size=1>{HLI_INIT_PRICE}</font></th>
				<th><font size=1>{HLI_INIT_QTY}</font></th>
				<th><font size=1>{HLI_INIT_DISCOUNT}</font></th>
				<th><font size=1>{HLI_INIT_TOTAL}</font></th>
				<th><font size=1>{HLI_TAX_RATE}</font></th>
				<th ><font size=1>{HLI_TAX_DESCRIPTION}</font></th>
				<th><font size=1>{HLI_TAX_AMOUNT}</font></th>
				<th><font size=1>{HLI_INIT_TOTAL_INCLUSIVE}</font></th>
			</tr>

			<patTemplate:tmpl name="rows" unusedvars="nbsp">
			<tr>
				<td colspan="3">{LI_NAME} {LI_DESCRIPTION}<br>{ROOMUID}</td>
				<td>{LI_INIT_PRICE}</td>
				<td>{LI_INIT_QTY}</td>
				<td>{LI_INIT_DISCOUNT}</td>
				<td>{LI_INIT_TOTAL}</td>
				<td>{LI_TAX_RATE}%</td>
				<td>{LI_TAX_DESCRIPTION}</td>
				<td>{LI_TAX_AMOUNT}</td>
				<td>{LI_INIT_TOTAL_INCLUSIVE}</td>
			</tr>
			</patTemplate:tmpl>
		
				<td colspan="9" height="70">Observaciones</td>
			</tr>
			<tr>
				<td colspan="9"><center><font size=0.1>TONOTOUR, ESTANCIAS VACACIONALES,S.L.
				Teléfono 922 xxxxxxx.<br></font></center></td>
			</tr>
		</thead>
	</table>
	<center><a href='javascript:window.print(); void 0;'>Imprimir</a></center>
</div>
</patTemplate:tmpl>



thank you very much again. I need your help please.

**Comment by bsweeney** [comment] 2016-02-29 18:18
Were I to guess I'd say the issue is the `<center>` element that isn't closed in the first cell of your table.

You also have an un-opened table row towards the end just before the cell that contains the text *Observaciones*.

dompdf isn't always able to handle structural issues like this so you should try to ensure your document validates (e.g. run the generated HTML through the [W3C validator](https://validator.w3.org/)). Or at the very least enable the HTML5 parser using `$dompdf->set_option('isHtml5ParserEnabled', true);`.

I'm going to leave this issue open to remind us to look at the code to see if we can improve error detection or method attribute typing in this code.

**Closed** 2016-04-04 00:20 UTC
Labels: bug, Priority-Low
