### ISSUE TITLE
Dejavu fonts are broken in 0.8.6

### ISSUE THREAD

**Issue by hustlahusky** [dompdf/dompdf#2298] opened 2020-11-17 15:56 UTC
It seems dejavu fonts are broken in 0.8.6

Same code snippet for generating pdf results to different outputs when switching dompdf versions between 0.8.5 and 0.8.6

```php
use Dompdf\Dompdf;

$content = <<<HTML
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
</head>
<body style="font-family: 'DejaVu Serif', serif;">Lorem ipsum</body>
</html>
HTML
;

$pdf = new Dompdf([
	'defaultPaperSize' => 'A4',
	'defaultPaperOrientation' => 'portrait',
]);
$pdf->loadHtml(mb_convert_encoding($content, 'HTML-ENTITIES', 'UTF-8'));
$pdf->render();
$pdf->stream('document.pdf', ['Attachment' => false]);
die();
```

When using dompdf version 0.8.5 it outputs pdf with text rendered:

![0.8.5](https://imgur.com/0wLp9rO.jpg)

After switching to version 0.8.6 text disapeared, but presents in file. Blue rectangle is a selection of a text.

![0.8.6](https://imgur.com/Np6R919.jpg)

**Comment by bsweeney** [comment] 2020-11-17 17:57
Using composer or the packaged download?

**Comment by hustlahusky** [comment] 2020-11-17 18:07
Dompdf installed using composer

**Comment by bsweeney** [comment] 2020-11-22 22:04
I'm not seeing the same issue switching between 0.8.5 and 0.8.6. Did anything else change with your system? Any errors in the PHP error logs? Can you post the output PDF so we can take a look at it?

**Comment by hustlahusky** [comment] 2020-11-25 09:33
It seems issue reproduced with ini setting `mbstring.func_overload=2` (which unfortunately required by framework)

I have prepared the repository with example how to reproduce this issue in docker repository https://github.com/hustlahusky/dompdf-issues. There's also an example to reproduce issue #2302 (without `mbstring.func_overload`)

**Comment by bsweeney** [comment] 2020-11-25 14:13
interesting ... lemme see what that would be, hopefully a quick fix since we mostly already use mbstring functions

**Comment by bsweeney** [comment] 2020-11-26 03:43
I wasn't able to reproduce changing only that setting, I'll have to take a look at your repo to see what I can find.

**Comment by biandishilaji** [comment] 2020-12-03 03:12
Hey dude, you check it ? 
https://github.com/dompdf/dompdf/issues/2302

**Comment by konstantin-s** [comment] 2021-01-28 12:28
> It seems issue reproduced with ini setting `mbstring.func_overload=2` (which unfortunately required by framework)
> 

Had same issue for me

I solved it with this modification of "phenx/php-font-lib" package (used by "dompdf/dompdf"):

https://github.com/konstantin-s/php-font-lib/commit/b1aa0c4c0ca3848780bdb33bde02fb869495b77a

**Comment by bsweeney** [comment] 2021-01-28 13:46
@konstantin-s that's a good find. Suggest you open an issue and/or pull request for the php-font-lib project.

**Comment by bsweeney** [comment] 2021-12-02 01:15
Function overloading was removed with PHP 8 so I'm going to close this issue.

To prevent potential issues down the road we'll still update php-font-lib to parse the binary data in 8bit mode.

**Closed by bsweeney** 2021-12-02 01:15 UTC
Labels: font-handling, dependencies
