### ISSUE TITLE
[0.8.0] Checkbox and Radio inputs are duplicated after a page break

### ISSUE THREAD

**Issue by pixelchutes** [dompdf/dompdf#1404] opened 2017-03-16 19:39 UTC
### Summary
When dealing with a long PDF resulting in multiple pages (2+), if you have a **checkbox** or **radio** element contained **within a block element** (e.g. `<div>`) that occurs _immediately_ after the page break, the resulting checkbox/radio is **rendered twice** _(e.g. duplicated)_.

### Step to reproduce
Try this source HTML using `v0.8.0`:

```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Duplicate Checkbox/Radio Example</title>
    <style>
        /* Forced height example */
        h1 { height: 900px; }
    </style>
</head>
<body>
    <h1>
        Example with height to force page break below:
    </h1>
    <div>
        <input type="checkbox"> Why does this now have TWO checkboxes immediately after the page break?
    </div>
</body>
</html>

```

### Observed behavior
The `checkbox` input displayed _after_ the page break gets duplicated (e.g. shown twice)

![dupe_check](https://cloud.githubusercontent.com/assets/352182/24015216/69286046-0a4d-11e7-81f7-0162ad41fe17.jpg)

The same occurs for `radio` inputs:

![dupe_radio](https://cloud.githubusercontent.com/assets/352182/24015236/829a012e-0a4d-11e7-9e14-29de1b9acc99.jpg)

I also tried other elements, like `<select>`, etc. They seem to get duplicated, too!

### Expected behavior
There is only one checkbox in the example markup. Therefore, only one should be rendered in the resulting PDF.

### Environment
domPDF v0.8.0 / PHP 5.6.30

**Comment by bsweeney** [comment] 2017-03-17 17:53
Looks to be an issue where the generated content (the actual checkbox or radio control) is re-generated on page break.

**Comment by dweingart** [comment] 2017-05-12 17:17
This might be related to issue #1434 where the same problem happens with CSS counters (which are also generated content).

**Comment by nickwuk** [comment] 2017-05-26 15:26
Experiencing the same issue.

**Comment by bsweeney** [comment] 2017-06-10 02:24
I believe this is addressed in the above commit.

**Comment by nickwuk** [comment] 2017-06-12 11:16
I've updated `src/Frame.php` and that removes the previous duplicate radio thank you, however the position of the first radio in the 2nd page is still offset.

![radio-bug-1404](https://user-images.githubusercontent.com/7723418/27031575-cbdf7a52-4f68-11e7-9876-4cd7c01d1e6c.jpg)

**Comment by bsweeney** [comment] 2017-06-12 13:43
Bummer. @nickwuk can you open a separate issue. I don't know if I'll have time fix this for the 0.8.1 release and I'd like to make sure we track it separately so it doesn't get lost.

**Comment by nickwuk** [comment] 2017-06-12 15:12
I believe I've located the offset issue to a font-family declaration in my particular theme css which is:
`font-family: 'Open Sans', sans-serif;`
and it's the `sans-serif` which seems to be the cause. Do you still want a new issue raising?

**Comment by bsweeney** [comment] 2017-06-12 15:14
That may help determine why, thanks. I think we still want a separate issue, though, since it's not directly related to the duplication.

**Closed** 2017-09-12 02:42 UTC
Labels: bug
