### ISSUE TITLE
Using DOMPDF with Twitter Bootstrap

### ISSUE THREAD

**Issue by creativecag** [dompdf/dompdf#631] opened 2013-05-06 15:29 UTC
Bootstrap seems to break output, yet my layout relies on it. Is there any fix for this?

**Comment by RSully** [comment] 2015-08-25 14:51
Have any changes been made for media query support? Bumping into this issue myself now.

**Comment by bsweeney** [comment] 2015-08-26 13:45
not as of yet, sorry :/

**Comment by vincekovacs** [comment] 2015-09-23 17:24
+1 for bootstrap support

**Comment by Soullivaneuh** [comment] 2015-10-02 11:15
:+1:

**Comment by eh1160** [comment] 2015-11-10 11:34
+1

**Comment by ajithfort** [comment] 2015-11-14 08:52
+1

**Comment by svenboogaart** [comment] 2015-12-27 16:20
+1

**Comment by mihai-craita** [comment] 2016-01-11 22:43
+1

**Comment by JoeriAben** [comment] 2016-01-17 13:55
+1

**Comment by dennerevaldt** [comment] 2016-01-28 20:16
+1

**Comment by kakaeriel** [comment] 2016-02-11 08:16
+1

**Comment by wjharil** [comment] 2016-02-15 19:06
+1

**Comment by mikeyb31** [comment] 2016-02-18 16:26
+1

**Comment by str** [comment] 2016-03-03 00:16
+1

**Comment by rosilva** [comment] 2016-03-08 23:19
+1

**Comment by lggdance** [comment] 2016-03-24 12:45
+1

**Comment by ruchikamayekar** [comment] 2016-04-01 13:42
Need support for bootstrap styling.

**Comment by ricardobarantini** [comment] 2016-04-04 22:08
+1

**Comment by iaroel** [comment] 2016-04-11 09:15
+1

**Comment by 0x1ad2** [comment] 2016-04-20 10:22
+1

**Comment by Kamisama666** [comment] 2016-04-20 10:51
+1

**Comment by jameshiggins** [comment] 2016-05-08 18:23
+1

**Comment by TarKHaoS** [comment] 2016-05-10 12:12
+1

**Comment by dmcgill50** [comment] 2016-05-10 15:44
+1

**Comment by pedrodj46** [comment] 2016-05-13 09:07
+1

**Comment by arnisjuraga** [comment] 2016-05-26 17:32
+1

**Comment by Elite40** [comment] 2016-06-02 17:17
+1

**Comment by arlina-espinoza** [comment] 2016-06-04 23:38
+1

**Comment by bsweeney** [comment] 2016-06-15 02:50
With the addition of support for `width: auto` by @scotteh dompdf now supports much of the basic Bootstrap styling.

We still have work to do so that we can support the Bootstrap grid (which, I know, is what the majority of you are seeking). Improvements around media queries and float handling should bring us closer to that goal.

Check out the develop branch if you're interested in checking out the improvements. After I update to the nightly generator you'll be able to download a packaged archive.

**Comment by Yppiti** [comment] 2016-06-17 19:11
+1

**Comment by SimeriaIonut** [comment] 2016-06-23 09:01
+1

**Comment by aleksandar-irvas** [comment] 2016-06-23 15:25
+1

**Comment by rubenppeters** [comment] 2016-06-27 06:47
+1

**Comment by IamSwap** [comment] 2016-06-28 06:03
+1

**Comment by raoulj** [comment] 2016-07-06 19:46
+1

**Comment by developer-lindner** [comment] 2016-07-11 12:26
+1 same for Foundation Sites, please

**Comment by fitoe** [comment] 2016-08-01 09:54
+1

**Comment by Jany-M** [comment] 2016-08-04 02:35
+1

Do you have any updates? @bsweeney
Elements collapse on each other when using nested floating elements, with % width.

**Comment by bsweeney** [comment] 2016-08-08 17:29
@Jany-M not really, I think changes being made for the 0.7.1 release should help, but I haven't fully tested yet to see what level of improvement we'll see.

**Comment by Mondaymarket** [comment] 2016-10-04 10:00
+1

**Comment by rahman5147** [comment] 2016-10-12 09:26
+1

**Comment by sergiodlopes** [comment] 2016-10-15 10:07
+1

**Comment by andrerademacher** [comment] 2016-11-21 14:21
+1 :)

**Comment by gidimuts** [comment] 2016-11-30 08:57
+1

**Comment by jaap115** [comment] 2017-01-11 09:56
+1

**Comment by meorajrul** [comment] 2017-01-18 07:06
+1

**Comment by chrBrd** [comment] 2017-02-02 19:12
I'm having what I assume to be the same problem @Jany-M had - top level columns display okay, but any nested inside those ignore row and column stylings and start floating on top of each other. Problem's still there on the 0.7.x-dev build.

**Comment by bsweeney** [comment] 2017-02-03 14:49
@chrBrd seen the same. I'm looking to further improve float support for the 0.7.2 release, which I hope will improve Bootstrap grid support.

**Comment by zeraist** [comment] 2017-02-13 15:07
+1

**Comment by pixelchutes** [comment] 2017-02-15 00:00
I just [posted a simplified example](https://github.com/dompdf/dompdf/issues/758#issuecomment-279869960) on the `:before`/`:after` issue in **0.7.0**, and I was able to boil it down to a very basic example.

The problem is that once you've included Bootstrap's CSS, there does not seem to be a way around it until #758 is fixed first.

**Comment by ajoaespinola** [comment] 2017-03-03 18:57
I just came here to leave my +1 :-)

**Comment by mkwsra** [comment] 2017-03-16 13:41
Same here

+1 😄

**Comment by crushcafeteria** [comment] 2017-04-02 14:20
+2. this issue was opened in 2015. i will try to contribute towards this. we direly need it

**Comment by enzofjh** [comment] 2017-04-12 07:01
+1.... four years later

**Comment by Blair2004** [comment] 2017-04-12 17:41
+1... for real since 2015 ??????

**Comment by Velliz** [comment] 2017-04-13 06:27
+1 for bootstrap support 👍

**Comment by seytone** [comment] 2017-05-18 19:00
+1 Very helpful library, but please, add bootstrap support. We need it 👍

**Comment by iaunn** [comment] 2017-06-08 15:26
+1

**Comment by cjessex** [comment] 2017-06-15 10:40
+1

**Comment by guiliredu** [comment] 2017-06-21 15:56
+1

**Comment by wimurk** [comment] 2017-07-11 07:40
+1

**Comment by AmandoVledder** [comment] 2017-07-11 07:41
+1 needing this

**Comment by peterbode1989** [comment] 2017-07-11 07:41
+1

**Comment by serter95** [comment] 2017-07-27 03:34
+1 need bootstrap in PDF documents please!

**Comment by brunocouty** [comment] 2017-08-01 03:10
Hello everybody! I resolve this problem using:

```
    $pdf = new Dompdf();
    $pdf->loadHtml($html);
    $pdf->setBasePath(public_path()); // This line resolve
    $pdf->render();
    $pdf->setPaper('A4');
    $pdf->stream('arquivo');
```

In your html, call like:
```
<link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" media="all">
```

But have a problem... In the link bellow, I read: 

[The main problem that you are having is the PDF converter is basically converting for a print screen. The max width for printing is much smaller than a browser.](https://stackoverflow.com/questions/36524277/dompdf-prints-html-bootstrap-code-as-col-sm-x-and-not-as-col-lg-x)

Well, this is real... I'm with a problem to format the file, because I only can use the "col-xs-*"...

Some idea?

**Comment by bsweeney** [comment] 2017-08-04 22:23
@brunocouty the print width bootstrap column sizing issue is real, but it's not the biggest issue we have. Still, if you want to see something other than the XS sizing try one or more of the following: increasing the Dompdf DPI setting, using landscape mode, using a larger paper size.

**Comment by surgiie** [comment] 2017-09-22 19:27
+1

**Comment by wimurk** [comment] 2017-09-26 10:27
Still no bootstrap support?

**Comment by bsweeney** [comment] 2017-09-26 14:55
There some minimal support right now. We're considering changes for the next release that may improve things a bit.

**Comment by gidimuts** [comment] 2017-10-06 04:38
+1

**Comment by Karador1995** [comment] 2017-10-13 15:06
+1

**Comment by NilLlisterri** [comment] 2017-11-15 09:44
+1

**Comment by mtx-z** [comment] 2017-11-19 00:08
+1

**Comment by phiterf** [comment] 2017-11-20 19:47
+1 must have

**Comment by wimurk** [comment] 2017-12-04 13:09
I have found a simple solution for the grid issue. Change the "DOMPDF_DPI" to fit the grid

**Comment by drkwolf** [comment] 2017-12-14 11:13
+1

**Comment by servetoz32** [comment] 2018-01-11 09:11
+1

**Comment by Soullivaneuh** [comment] 2018-01-11 09:24
> I have found a simple solution for the grid issue. Change the "DOMPDF_DPI" to fit the grid

@wimurk could you please elaborate? Maybe add some examples?

**Comment by wimurk** [comment] 2018-01-12 14:47
@Soullivaneuh the problem with dompdf is that its grid is not compatible with dompdfs DPI.

col-md-12 will result in a div outside the pdf sheet. When you change the DPI the grid will fit just fine.

**Comment by enzofjh** [comment] 2018-01-12 16:23
Where should I change te DPI??

Can you please provide an example?

**Comment by adriencohen** [comment] 2018-02-01 14:56
@enzofjh Setting the DPI like this will get you the grid to better fit the pdf file

```php
$options = new \Dompdf\Options();
$options->setDpi(150);
$dompdf = new \Dompdf($options);
```

**Comment by enzofjh** [comment] 2018-02-01 15:06
thank you, I will try it

**Comment by recopv** [comment] 2018-02-09 18:27
+1

**Comment by ahmadsyamim** [comment] 2018-02-14 05:04
thank you, grid working fine when set the dpi. Thank you a lot.

> @enzofjh Setting the DPI like this will get you the grid to better fit the pdf file

$options = new \Dompdf\Options();
$options->setDpi(150);
$dompdf = new \Dompdf($options);

**Comment by recopv** [comment] 2018-02-14 05:25
Thanks for response, appreciate it

**Comment by alissonalberini** [comment] 2018-11-05 17:13
+1 for bs

**Comment by josegus** [comment] 2018-11-16 16:08
+5

**Comment by oghenez** [comment] 2020-11-12 11:47
> Still no bootstrap support? shame

this is not encouraging for a free software

**Comment by bsweeney** [comment] 2022-08-21 20:13
Going to go ahead and close this issue. Bootstrap is a comprehensive framework so "making Dompdf compatible" with it would be a project in and of itself, requiring checklists and separate tickets. For now we'll continue to focus on individual CSS feature support (e.g., Flexbox #971) that will help improve compatibility as those feature are developed.

**Closed by bsweeney** 2022-08-21 20:13 UTC

**Comment by jhoanborges** [comment] 2023-01-02 23:54
+1 bootstrap support

**Comment by ttimot24** [comment] 2024-03-28 14:23
+1
