### ISSUE TITLE
Tables column widths are not consistent across pages

### ISSUE THREAD

**Issue by PhenX** [dompdf/dompdf#55] opened 2012-12-06 21:07 UTC
_Original author: pedro.gu...@gmail.com (July 30, 2009 22:08:46)_

<b>What steps will reproduce the problem?</b>
1. Create a 2 page HTML nested table
2. Render the HTML and generate PDF

<b>What is the expected output? What do you see instead?</b>
Nested table looses alignment and formatting when breaking to page number
two. The table comming from page one should continue on page 2 preserving
the text and row proportions.

<b>What version of the product are you using? On what operating system?</b>
0.5.1
CentOs 5/ Apache2 / PHP5

<b>Please provide any additional information below.</b>
Please note the bogus table break at the second page of the attached document. 

_Original issue: http://code.google.com/p/dompdf/issues/detail?id=48_

**Comment by loren138** [comment] 2016-07-07 14:21
This probably isn't an exact replica, but hopefully it will help.  I've done everything I can think to make the widths match (and they do in browser).

HTML: http://codepen.io/anon/pen/AXoxvY
[quickReference.pdf](https://github.com/dompdf/dompdf/files/352336/quickReference.pdf)

**Comment by simonberger** [comment] 2020-02-19 00:21
Duplicate of #1388

**Closed** 2020-02-19 00:21 UTC
Labels: Priority-Medium, bug, imported
