### ISSUE TITLE
"Frame not found in cellmap" on rowspanned cells only if border-collapse

### ISSUE THREAD

**Issue by vstefanoxx** [dompdf/dompdf#657] opened 2013-06-04 23:17 UTC
How to reproduce:
- table with rowspanned column that doesn't fit in one page AND only if "border-collapse: collapse" css style on table is used

If no "border-collapse: collapse" is used, error doesn't happen but cells are not rendered correctly on 2nd page (2nd column cell is rendered on 1st column)

Additional info:
- PHP versione 5.3.8
- dompdf v. 0-6-0_beta3
- server Apache on Windows (XAMPP)
- HTML code: see below

Maybe duplicate of [#68](https://github.com/dompdf/dompdf/issues/68)
but in this case happens only if setting "border-collapse: collapse" css style on table.

I also tried Yariv's fix suggested in [#68](https://github.com/dompdf/dompdf/issues/68) and dontbreak="true", but in this case page timeout with error:

```
Fatal error: Maximum execution time of 30 seconds exceeded in I:\xampp\htdocs\myreg\includes\dompdf\include\frame.cls.php on line 321"
```

Here is the stack trace of "Frame not found in cellmap" error:

```
Message: Frame not found in cellmap
File: I:\xampp\htdocs\myreg\includes\dompdf\include\cellmap.cls.php
Line: 212
Trace

#0 I:\xampp\htdocs\myreg\includes\dompdf\include\table_cell_renderer.cls.php(51): Cellmap->get_spanned_cells(Object(Table_Cell_Frame_Decorator))
#1 I:\xampp\htdocs\myreg\includes\dompdf\include\renderer.cls.php(283): Table_Cell_Renderer->render(Object(Table_Cell_Frame_Decorator))
#2 I:\xampp\htdocs\myreg\includes\dompdf\include\renderer.cls.php(117): Renderer->_render_frame('table-cell', Object(Table_Cell_Frame_Decorator))
#3 I:\xampp\htdocs\myreg\includes\dompdf\include\renderer.cls.php(185): Renderer->render(Object(Table_Cell_Frame_Decorator), false)
#4 I:\xampp\htdocs\myreg\includes\dompdf\include\renderer.cls.php(185): Renderer->render(Object(Table_Row_Frame_Decorator), false)
#5 I:\xampp\htdocs\myreg\includes\dompdf\include\renderer.cls.php(185): Renderer->render(Object(Table_Row_Group_Frame_Decorator), false)
#6 I:\xampp\htdocs\myreg\includes\dompdf\include\renderer.cls.php(185): Renderer->render(Object(Table_Frame_Decorator), false)
#7 I:\xampp\htdocs\myreg\includes\dompdf\include\page_frame_reflower.cls.php(147): Renderer->render(Object(Block_Frame_Decorator))
#8 I:\xampp\htdocs\myreg\includes\dompdf\include\frame_decorator.cls.php(556): Page_Frame_Reflower->reflow(NULL)
#9 I:\xampp\htdocs\myreg\includes\dompdf\include\dompdf.cls.php(817): Frame_Decorator->reflow()
```

Here is HTML page used:

```
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <style type="text/css">
        table {
            border-collapse: collapse;
            border: 1 #000000 solid;
        }
        table td {
            border: 1 #000000 solid;
        }
    </style>
</head>

<body>
    <table width="10%">
        <thead>
            <tr>
                <th>Col1</th>
                <th>Col2</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td rowspan="2">
                    Col1 Rowspan x
                    <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
                    Col1 Rowspan y
                    <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
                    Col1 Rowspan z
                </td>
                <td>
                    Col2 Row2.1
                </td>
            </tr>

            <tr>
                <td>Col2 Row2.2</td>
            </tr>

        </tbody>
    </table>
</body>
</html>
```

**Comment by martinlazarov** [comment] 2015-09-18 15:37
18.09.2015 - Have the developers had some time to fix it because it still breaks the conversion?

**Comment by bsweeney** [comment] 2015-09-18 17:11
Yes ... ish. The fatal error was fixed by c081dbd9a6fc64f7ec7633c9446a3f061ced85fc (ref #961). The resulting render isn't perfect, but dompdf will no longer crash. Check out the develop branch or [grab a nightly](http://eclecticgeek.com/dompdf-info/).

**Comment by nidhiyadav3** [comment] 2015-10-01 06:58
You can use a custom paper size. It will solve the problem.

Example :
$paper_orientation = 'landscape';
$customPaper = array(0,0,950,950);
$dompdf->set_paper($customPaper,$paper_orientation);

**Comment by pbranthome** [comment] 2015-11-10 15:05
Is there any solution with a good render for this issue ????

**Comment by bsweeney** [comment] 2015-11-10 15:08
Solution? Yes. A good render? Not yet. As noted above this will render in 0.7.0 but the output is not great.

**Comment by larsjanssen6** [comment] 2016-01-18 17:06
It still crashes: Frame not found in cellmap

**Comment by JontyNewman** [comment] 2016-01-19 15:13
I also experienced this bug today. I can confirm it was due to a border-collapse on a table that extended across to another page.

**Comment by bsweeney** [comment] 2016-01-19 18:35
In which version of dompdf? HTML sample?

**Comment by mdhama** [comment] 2017-03-17 08:31
Error occurred when I use `display:table-cell;` css style.

**Comment by bsweeney** [comment] 2017-03-17 17:46
@mdhama do you have a complete sample that reproduces the error.

**Comment by uglyeoin** [comment] 2017-05-22 13:12
I do.  We have created a plugin for Joomla! so ignore any references as such the PDF will render in <div>s just not <tables>

```
<?php
?>
<?php
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<style>
		/* ROBOTO SLAB */
		/* cyrillic-ext */
		@font-face {
		  font-family: 'Roboto Slab';
		  font-style: normal;
		  font-weight: 400;
		  src: local('Roboto Slab Regular'), local('RobotoSlab-Regular'), url(https://fonts.gstatic.com/s/robotoslab/v6/y7lebkjgREBJK96VQi37ZjTOQ_MqJVwkKsUn0wKzc2I.woff2) format('woff2');
		  unicode-range: U+0460-052F, U+20B4, U+2DE0-2DFF, U+A640-A69F;
		}
		/* cyrillic */
		@font-face {
		  font-family: 'Roboto Slab';
		  font-style: normal;
		  font-weight: 400;
		  src: local('Roboto Slab Regular'), local('RobotoSlab-Regular'), url(https://fonts.gstatic.com/s/robotoslab/v6/y7lebkjgREBJK96VQi37ZjUj_cnvWIuuBMVgbX098Mw.woff2) format('woff2');
		  unicode-range: U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116;
		}
		/* greek-ext */
		@font-face {
		  font-family: 'Roboto Slab';
		  font-style: normal;
		  font-weight: 400;
		  src: local('Roboto Slab Regular'), local('RobotoSlab-Regular'), url(https://fonts.gstatic.com/s/robotoslab/v6/y7lebkjgREBJK96VQi37ZkbcKLIaa1LC45dFaAfauRA.woff2) format('woff2');
		  unicode-range: U+1F00-1FFF;
		}
		/* greek */
		@font-face {
		  font-family: 'Roboto Slab';
		  font-style: normal;
		  font-weight: 400;
		  src: local('Roboto Slab Regular'), local('RobotoSlab-Regular'), url(https://fonts.gstatic.com/s/robotoslab/v6/y7lebkjgREBJK96VQi37Zmo_sUJ8uO4YLWRInS22T3Y.woff2) format('woff2');
		  unicode-range: U+0370-03FF;
		}
		/* vietnamese */
		@font-face {
		  font-family: 'Roboto Slab';
		  font-style: normal;
		  font-weight: 400;
		  src: local('Roboto Slab Regular'), local('RobotoSlab-Regular'), url(https://fonts.gstatic.com/s/robotoslab/v6/y7lebkjgREBJK96VQi37Zr6up8jxqWt8HVA3mDhkV_0.woff2) format('woff2');
		  unicode-range: U+0102-0103, U+1EA0-1EF9, U+20AB;
		}
		/* latin-ext */
		@font-face {
		  font-family: 'Roboto Slab';
		  font-style: normal;
		  font-weight: 400;
		  src: local('Roboto Slab Regular'), local('RobotoSlab-Regular'), url(https://fonts.gstatic.com/s/robotoslab/v6/y7lebkjgREBJK96VQi37ZiYE0-AqJ3nfInTTiDXDjU4.woff2) format('woff2');
		  unicode-range: U+0100-024F, U+1E00-1EFF, U+20A0-20AB, U+20AD-20CF, U+2C60-2C7F, U+A720-A7FF;
		}
		/* latin */
		@font-face {
		  font-family: 'Roboto Slab';
		  font-style: normal;
		  font-weight: 400;
		  src: local('Roboto Slab Regular'), local('RobotoSlab-Regular'), url(https://fonts.gstatic.com/s/robotoslab/v6/y7lebkjgREBJK96VQi37Zo4P5ICox8Kq3LLUNMylGO4.woff2) format('woff2');
		  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2212, U+2215;
		}	

		/* OPEN SANS */
		/* cyrillic-ext */
		@font-face {
		  font-family: 'Open Sans';
		  font-style: normal;
		  font-weight: 400;
		  src: local('Open Sans'), local('OpenSans'), url(https://fonts.gstatic.com/s/opensans/v13/K88pR3goAWT7BTt32Z01mxJtnKITppOI_IvcXXDNrsc.woff2) format('woff2');
		  unicode-range: U+0460-052F, U+20B4, U+2DE0-2DFF, U+A640-A69F;
		}
		/* cyrillic */
		@font-face {
		  font-family: 'Open Sans';
		  font-style: normal;
		  font-weight: 400;
		  src: local('Open Sans'), local('OpenSans'), url(https://fonts.gstatic.com/s/opensans/v13/RjgO7rYTmqiVp7vzi-Q5URJtnKITppOI_IvcXXDNrsc.woff2) format('woff2');
		  unicode-range: U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116;
		}
		/* greek-ext */
		@font-face {
		  font-family: 'Open Sans';
		  font-style: normal;
		  font-weight: 400;
		  src: local('Open Sans'), local('OpenSans'), url(https://fonts.gstatic.com/s/opensans/v13/LWCjsQkB6EMdfHrEVqA1KRJtnKITppOI_IvcXXDNrsc.woff2) format('woff2');
		  unicode-range: U+1F00-1FFF;
		}
		/* greek */
		@font-face {
		  font-family: 'Open Sans';
		  font-style: normal;
		  font-weight: 400;
		  src: local('Open Sans'), local('OpenSans'), url(https://fonts.gstatic.com/s/opensans/v13/xozscpT2726on7jbcb_pAhJtnKITppOI_IvcXXDNrsc.woff2) format('woff2');
		  unicode-range: U+0370-03FF;
		}
		/* vietnamese */
		@font-face {
		  font-family: 'Open Sans';
		  font-style: normal;
		  font-weight: 400;
		  src: local('Open Sans'), local('OpenSans'), url(https://fonts.gstatic.com/s/opensans/v13/59ZRklaO5bWGqF5A9baEERJtnKITppOI_IvcXXDNrsc.woff2) format('woff2');
		  unicode-range: U+0102-0103, U+1EA0-1EF9, U+20AB;
		}
		/* latin-ext */
		@font-face {
		  font-family: 'Open Sans';
		  font-style: normal;
		  font-weight: 400;
		  src: local('Open Sans'), local('OpenSans'), url(https://fonts.gstatic.com/s/opensans/v13/u-WUoqrET9fUeobQW7jkRRJtnKITppOI_IvcXXDNrsc.woff2) format('woff2');
		  unicode-range: U+0100-024F, U+1E00-1EFF, U+20A0-20AB, U+20AD-20CF, U+2C60-2C7F, U+A720-A7FF;
		}
		/* latin */
		@font-face {
		  font-family: 'Open Sans';
		  font-style: normal;
		  font-weight: 400;
		  src: local('Open Sans'), local('OpenSans'), url(https://fonts.gstatic.com/s/opensans/v13/cJZKeOuBrn4kERxqtaUH3VtXRa8TVwTICgirnJhmVJw.woff2) format('woff2');
		  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2212, U+2215;
		}

		/* CSS */
        table {
            border-collapse: collapse;
        }			
		.container {
			width: 21cm;
			height: 29.7cm; 
			padding: 1.37cm 0.97cm 1.41cm;
		}

		/*
		.inner {
			width: 100%;
			height: 100%;
		}
		*/
		.row {
			width: 100%;
			display: block;
			float: left;
		}
		.heading {
			font-family: 'Roboto Slab', serif;
			line-height: 17.13mm;
			font-size: 1.552cm;
			color: #F5791F;
			/* font-weight: bold; */
		}
		p {
			font-family: 'Open Sans', sans-serif;
		}
		.size-50 {
			width: 50%;
			display: inline-block;
			float:left;
		}
		.content.size-50 {
			height: 9.97cm;
		}
		.content.size-50 > div {
			height: 9.7cm;
		}
		.bottomLine {
			position: relative;
			bottom: 0;
			height: 0.22cm;
		}
		.bottomLine img {
			width: 100%;
/*			height: auto; */
		}

		/* Images */
		img {max-width: 100%;}
		.logo {
			width: 4.6cm;
			height: 1.33cm;
		}
		.content.logo {
			float:right;
			margin-bottom: 0.85cm;
		}
		.mainImage {
			width: 100%;
			height: auto;
		}
		/* html, div {page-break-inside:avoid;} */
	</style>
</head>

<body>
	<table class="container">
		<tr>
			<td>
				<table class="inner">
					<tr class="logoRow row">
						<td class="content logo">
							<img src="plugins/system/pdfgenerator/tmpl/logo.jpg" alt="logo" class="logo">
						</td>
					</tr>
					<tr class="row">
						<td class="content heading">
							<span class="heading">Commercial Mortgages,<br>
							revinented</span>
						</td>
					</tr>		
					<tr class="row">
						<div class="content mainImage">
							<img src="plugins/system/pdfgenerator/tmpl/mainImage.jpg" alt="">
						</div>
					</div>

					<tr class="row">
						<td>
							<table>
								<tr>
									<td>
										<p>Dear </p>
										<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.
										</p>
										<p>Quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
										</p>
										<p>That said there are some details we really must share:</p>				
									</td>
								</tr>
								<tr>
									<td class="content size-50">
										<span class="para1">
											<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.
											</p>
											<p>Quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
											</p>
											<p>That said there are some details we really must share:</p>
										</span>
										<div class="bottomLine">
											<img src="plugins/system/pdfgenerator/tmpl/line.jpg" alt="" class="bottomLine">	
										</div>
									</td>
								</tr>
								<tr>
									<td class="content size-50 map">
										<img src="plugins/system/pdfgenerator/tmpl/map.jpg" alt="" class="map">
									</td>			
								</tr>
							</table>
						</td>
					</tr>						
				</table>
				</td>
			</tr>
		</table>
</body>
</html>
```

**Comment by bsweeney** [comment] 2017-07-31 15:05
@uglyeoin thanks for the sample. Your sample does have a few structural issues that could cause problems for Dompdf, but even after cleaning those up it does indeed throw that exception. This should be helpful in tracking down the issue.

**Comment by uglyeoin** [comment] 2017-08-01 10:11
@bsweeney Oh yes, I see them, my apologies.  Glad it helps, thanks for the great software.

**Comment by claytonrcarter** [comment] 2017-08-08 19:25
I was stuck on this Exception for a while. It ended up being poorly formatted HTML w/ a `<th>` being placed outside of a `<tr>`. After correcting the HTML structure, the Exception has not resurfaced.

**Comment by cauehqueiroz** [comment] 2017-08-17 18:20
[PDF BUG.txt](https://github.com/dompdf/dompdf/files/1232223/PDF.BUG.txt)
I'm also having the same problem @bsweeney , in this case if a `<tr>` with `rowspan` attribute gets between pages it throws the same exception. 
😞 
I've added the HTML (PDF BUG,txt), hope you can solve it.
Anyway, thanks for DOMPDF, it is great!

**Comment by bsweeney** [comment] 2017-08-24 23:57
@cauehqueiroz rowspan on a TR element? That wouldn't be valid HTML. But looking at your sample I think you mean the rowspan is on the TD element.

That's a large sample, it makes debugging hard. But we'll take a look. It would help to have a bit more information. For example, which version of Dompdf are you using? What's the page size? Is the HTML5 parser enabled?

**Comment by AdnanBoota** [comment] 2018-06-27 15:36
same issue here, any solution for this?

![image](https://user-images.githubusercontent.com/14972616/41984284-97792eb8-7a30-11e8-8dff-b7f01b3f861c.png)

**Comment by godfreymakori** [comment] 2019-06-11 08:18
Check on wrongly placed/unclosed/wrongly closed HTML tags

**Comment by redheadedstep** [comment] 2019-07-10 17:31
Check that you don't have any `<` or `>` as just text (something like ```"Are you < 21 years old?"```).  I had these in my text (which was entered by users) and was not running them through `htmlentitities` before I created the PDF.

**Comment by iamravimane** [comment] 2019-12-11 12:14
check any closing tag is missed.

**Closed** 2020-01-23 03:33 UTC
Labels: duplicate

**Comment by bsweeney** [comment] 2020-01-23 03:35
Closing since the original issue has been identified as a duplicate of 98.

For those of you with potentially bad HTML syntax, try enabling the HTML5 parser. It's designed to try and clean that up.

**Comment by bunday** [comment] 2020-02-04 11:48
I have this issue. It happens whenever I add a `display: flex` to a tag

**Comment by bsweeney** [comment] 2020-02-05 01:29
@bunday we haven't yet implemented `display: flex`, you can watch #971 for updates on that.

I'm not seeing a similar issue to feel free to post sample HTML+CSS to 971 for follow-up.

**Comment by bunday** [comment] 2020-02-05 09:25
Hi, Thanks for your reply. When you have a sample code like `display: flex; justify-content: space-between;` it crashes. I had to resolve back to using `float` and `margin` to handle spacing

**Comment by tusharkhan** [comment] 2022-08-20 20:45
just dont use ``display: flex; ``
