### ISSUE TITLE
Rendering pdf file sometimes leaves artifact

### ISSUE THREAD

**Issue by gbonnema** [dompdf/dompdf#1226] opened 2016-06-30 12:00 UTC
PHP 5.6.21-2
Debian 3.16.3-2 (2014-09-20)

I cannot find the DomPDF version in the source code. 

When generating a PDF document, the result is mostly fine (no artifact), but once every 10-20 attempts, the result has an artifact over the result as if a part of the graphics where taken with a low resolution / grainy lens. I can provide a screenshot of the problem but am restricted by my company to upload it for the public to see. How can I send you the screenshot?

Is this a known problem with a certain release of DomPDF or has this been fixed in a certain version already?

**Comment by bsweeney** [comment] 2016-07-03 00:33
The most relevant issue I've seen is due to a problem with GMagick/IMagick PHP module support. Do you have either of those modules enabled?

**Comment by gbonnema** [comment] 2016-07-04 07:43
Apparantly we use  ImageMagick version 6.8.9-6 Q16 x86_64. Do you have a link to the most relevant issue? Is there a resolution?

**Comment by bsweeney** [comment] 2016-07-05 15:00
I think maybe #920 is the most recent relevant issue, though this goes back as far as #432. There are a few other issues as well. Took a while to track it down so the issues aren't all correlated.

FYI, the quickest work around is to disable the library. But if that's not possible you can modify the conditionals that check for that extension to always be false in the [Cpdf library](https://github.com/dompdf/dompdf/blob/v0.7.0/lib/Cpdf.php#L4366).

**Comment by bobkruithof** [comment] 2016-07-06 08:14
I don't think this is related to #432. I see how this issue and issue #920 are probable related but #432 doesn't seem to have artefacts. Anyway, will this problem be tackled in the upcoming release?

**Comment by bsweeney** [comment] 2016-07-06 20:29
You are correct, what I mean to say is that the fix proposed in 432 (adding a configurable option) is probably how we will address the issue until we figure out exactly what's going on. The option will be added to 0.7.1.

**Comment by bsweeney** [comment] 2017-02-16 02:50
sorry ... booting to the next release

**Comment by bsweeney** [comment] 2017-11-20 02:53
Merged a fix for IMagick issues in commit c68484c. If anyone can confirm the issue is resolved that would be great. The update will be included in 0.8.2.

**Closed** 2017-11-21 04:27 UTC
Labels: bug, duplicate
