### ISSUE TITLE
Position of underline in fonts generated through load_font

### ISSUE THREAD

**Issue by php-prince** [dompdf/dompdf#846] opened 2014-07-24 03:06 UTC
I'm using the latest version of dompdf, downloaded today from Github.

I generated the Calibri font through load_font, using the following command:

php load_font.php Calibri calibri.ttf calibrib.ttf calibrii.ttf calibriz.t
tf

Everything appeared to work; however the position of underlines (including anchor underlines) is significantly higher than it should be, appearing as a low strike-through.

Previously, I had an older version of dompdf, where the problem was worse (the line was even higher). I think there is some error in the calculation of the font's metrics. 

Fonts that come dompdf work correctly, so I do think it's something to do with the font creation engine and the generated metrics.

As an additional piece of information, I also noticed that, when using this font, if I enclosed it in a div with equal upper and lower padding (say, 10px) it would not appear centered. However, if I use one of the fonts supplied with dompdf, it centers correctly.

This old issue might refer to a similar problem:

**Comment by Lutacon** [comment] 2015-03-06 11:32
I have the same problem with a Google Font(Signika)

**Comment by bsweeney** [comment] 2015-03-07 03:53
@Lutacon though I can't tell you where, right now, the issue lies (dompdf, php-font-lib, or the font itself), I can say that if you modify the font metrics file (UFM) you can tweak the underline position by changing the value of `UnderlinePosition`.

**Comment by soe7** [comment] 2015-11-24 11:28
Hi, I am experiencing same issue. Where about is the font metrics file is located ?

Thanks in advance

**Comment by bsweeney** [comment] 2015-11-24 15:10
You can find the font metrics in the location specified by DOMPDF_FONT_DIR. In a vanilla copy of dompdf that would be under dompdf/lib/fonts. Look for a file with the same name as the font file (or hash for `@font-face`-loaded fonts) ending with .UFM.

**Comment by inbaz** [comment] 2017-04-08 17:32
I encountered the same problem. There is a .ufm and a .ufm.php file in my dompdf/lib/fonts folder. I needed to change the .ufm.php file to have the changes take effect. For my OpenSans-Regular font it needed 'UnderlinePosition' => '-500' instead of -75. Maybe for somebody who finds that thread it helps to have a clue in which dimensions you need to calculate to see the effects of the changes.

**Comment by bsweeney** [comment] 2017-04-11 22:41
Instead of changing the .ufm.php file I'd recommend changing the .ufm file and deleting the .ufm.php file, which is a cache file generated by dompdf when it first parses a font.

**Comment by bsweeney** [comment] 2018-06-27 02:09
With the upcoming release I believe this work-around will no longer be necessary.

Closing as a duplicate of #609. Please follow that issue for updates.

**Closed by bsweeney** 2018-06-27 02:09 UTC
Labels: bug, duplicate, font-handling

**Comment by Alisa-Margaryan** [comment] 2023-10-10 14:50
Hello everyone, I have an issue with links as well when using Japanese font from Google font ("Noto Sans JP", sans-serif), 
My package versions are:
  "name": "barryvdh/laravel-dompdf",  "version": "v0.8.2",
  "dompdf/dompdf": "^0.8"
 can you please offer me something to fix it?
![image (23)](https://github.com/dompdf/dompdf/assets/77612455/29a36d89-f9ad-41b6-8b79-bee801dd1c96)

**Comment by bsweeney** [comment] 2023-10-10 16:38
@Alisa-Margaryan you should migrate to the latest release. But if you have reasons for sticking to the 0.8.x version you should at least move to 0.8.3, which appears to address that issue. Have you tried running `composer update`? Might need to move to a newer version of laravel-dompdf

**Comment by Alisa-Margaryan** [comment] 2023-10-11 07:55
@bsweeney thank you for support, for now I can't update my composer because our project is large and it will bring other issues I wondering, but will try to create other project for pdf rendering :)

**Comment by bsweeney** [comment] 2023-10-11 14:22
FYI going from your current version of Dompdf to the 0.8.3 release should be a drop-in replacement if you want to do it manually.
