### ISSUE TITLE
colspan td width issue (0.8.3)

### ISSUE THREAD

**Issue by VlLight** [dompdf/dompdf#1907] opened 2019-03-18 18:25 UTC
Hello. I have a trouble with "colspaned" td rendering with version 0.8.3
This html renders good
```
<table style="width: 700px;" cellpadding="0" cellspacing="0" border="1">
	<tr>
		<td style="width: 685px;">1</td>
		<td style="width: 15px;">2</td>
	</tr>
</table>
```
![screen_01](https://user-images.githubusercontent.com/5028278/54553241-cf2fa500-49c2-11e9-84cf-b093d6e0bc83.png)
But if I add colspaned td and, in next row, one wide column and one narrow column (685px | 15px), it renders in unusual way:
```
<table style="width: 700px;" cellpadding="0" cellspacing="0" border="1">
	<tr>
		<td colspan="2" style="width: 700px;">3</td>
	</tr>
	<tr>
		<td style="width: 685px;">1</td>
		<td style="width: 15px;">2</td>
	</tr>
</table>
```
![screen_02](https://user-images.githubusercontent.com/5028278/54553717-de632280-49c3-11e9-84ff-5926082cc80c.png)

While, if I use (350px | 350px) columns instead, it renders good.
```
<table style="width: 700px;" cellpadding="0" cellspacing="0" border="1">
	<tr>
		<td colspan="2" style="width: 700px;">3</td>
	</tr>
	<tr>
		<td style="width: 350px;">1</td>
		<td style="width: 350px;">2</td>
	</tr>
</table>
```
![screen_03](https://user-images.githubusercontent.com/5028278/54553775-03f02c00-49c4-11e9-8156-2f4a7fa3c816.png)
Is there any solution for this case?

**Comment by bsweeney** [comment] 2019-05-10 01:06
Sadly I do not have a solution for you at this time. It's a function of how dompdf links table cells. Obviously needs some work.

**Comment by basven1997** [comment] 2020-09-19 15:46
Is their already a salution for this bug?

**Comment by bsweeney** [comment] 2020-09-20 16:09
no solution yet

**Comment by bsweeney** [comment] 2020-11-24 14:10
possibly related to #1131

**Comment by bsweeney** [comment] 2020-11-26 03:38
Tentatively identified the issue as [this block of code in the cellmap class](https://github.com/dompdf/dompdf/blob/v0.8.6/src/Cellmap.php#L677-L694):

```
            if ($frame_min > $min) {
                // The frame needs more space.  Expand each sub-column
                // FIXME try to avoid putting this dummy value when table-layout:fixed
                $inc = ($this->is_layout_fixed() ? 10e-10 : ($frame_min - $min) / $colspan);
                for ($c = 0; $c < $colspan; $c++) {
                    $col =& $this->get_column($this->__col + $c);
                    $col["min-width"] += $inc;
                }
            }

            if ($frame_max > $max) {
                // FIXME try to avoid putting this dummy value when table-layout:fixed
                $inc = ($this->is_layout_fixed() ? 10e-10 : ($frame_max - $max) / $colspan);
                for ($c = 0; $c < $colspan; $c++) {
                    $col =& $this->get_column($this->__col + $c);
                    $col["max-width"] += $inc;
                }
            }
```

The issue is the even distribution of the minimum/maximum width of colspanned cells across columns. What that means is that in this example:

```
<table style="width: 700px;" cellpadding="0" cellspacing="0" border="1">
	<tr>
		<td colspan="2" style="width: 700px;">3</td>
	</tr>
	<tr>
		<td style="width: 685px;">1</td>
		<td style="width: 15px;">2</td>
	</tr>
</table>
```

even though the second column should have a minimum width of 15px it is given a minimum of 350px because of the colspanned cell. This particular issue can be resolved by excluding colspanned cells from the minimum, but that change alone isn't sufficient for all cases.

**Closed** 2020-11-26 23:17 UTC
Labels: bug, layout, tables
