### ISSUE TITLE
background-size not working

### ISSUE THREAD

**Issue by maartenhetworks** [dompdf/dompdf#1693] opened 2018-03-19 19:22 UTC
Background-size is not working properly

`
@page {
            margin: 0;
}
html, body {
            background-image: url(url);
            background-repeat: no-repeat;
            background-position: bottom right;
            background-size: 100px;
            margin: 0;
            width: 100%;
            height: 100%;
}`

It ignores the background-size property. I can see the background image but it is to large.

**Comment by simonberger** [comment] 2018-03-19 19:53
Duplicate of #463

**Closed by simonberger** 2018-03-19 19:53 UTC

**Comment by WebSpectrum** [comment] 2019-08-13 02:57
any workaround for this to get a similiar result? I want to use CSS property baackground-size:cover ?? .... thanks

**Comment by bsweeney** [comment] 2019-09-09 02:21
The closest you could get would be to absolutely position a div with z-index (to move it behind other content). The only element inside the DIV would be the image sized horizontally or vertically as appropriate to simulate a cover.

**Comment by Keania-Eric** [comment] 2020-01-14 09:19
I solved my problem by using a graphical tool to resize the background image to exactly the size of the frame to render it. And that actually i think is best.
