### ISSUE TITLE
PNG images showing up as white if utilizing ImageMagick

### ISSUE THREAD

**Issue by PhenX** [dompdf/dompdf#432] opened 2012-12-06 22:02 UTC
_Original author: kzeni1 (February 15, 2012 15:46:26)_

<b>What steps will reproduce the problem?</b>
1. Include a PNG image w/ a full alpha channel in the page's content (PNG images with binary transparency seem to be fine).
2. Have a server with ImageMagick 2.2.1 (at least this is what my server has [Rackspace Cloud]).
3. Generate PDF.

<b>What is the expected output? What do you see instead?</b>
The image should look like it does on the webpage. Instead, it shows the image as being completely white while retaining the alpha channel (ex. a circular image with a logo &amp; transparent background just ends up showing as a white circle).

<b>What version of dompdf are you using? What version of PHP? On what</b>
<b>operating system?</b>
dompdf 0.6 beta 3

<b>Please provide the HTML source code you want to convert, or any additional</b>
<b>information.</b>
Some investigation showed that the problem was the utilization of imagick. I found a fix that involves disabling imagick's PNG rendering &amp; using the fallback image rendering instead (including it as an option in the config file so people can still use imagick if it works for them).
- Add the following line to &quot;dompdf_config.custom.inc.php&quot;:
  define(&quot;DOMPDF_ENABLE_IMAGICK&quot;, false);
- Change line 4324 of &quot;class.pdf.php&quot; from:
  elseif (extension_loaded(&quot;imagick&quot;)) {
- to:
  elseif (extension_loaded(&quot;imagick&quot;) &amp;&amp; DOMPDF_ENABLE_IMAGICK) {

This makes it so the configuration file is disabling the buggy PNG processing. I looked into the color channels &amp; imagick implementation to see if there was an issue there, but I didn't find anything wrong with it in my brief time looking through it. Also, you could set up a similar config option for gmagick .

_Original issue: http://code.google.com/p/dompdf/issues/detail?id=426_

**Comment by marrch-caat** [comment] 2017-06-29 10:28
I still would be glad if this problem is fixed. We are now facing the same problem with transparent gif/png images that ain't processed correct with ImageMagic, though GD treats them properly, and if I re-save the image converted with GD, it will then work fine in ImageMagic as well. We can't disable ImageMagic extension in our project, so we'd be glad to have an option to prevent domPDF from using it.

**Comment by bsweeney** [comment] 2017-07-13 02:53
I was hoping to have something done for the 0.8.0 release, but I had to push it off. I don't think I'll have time to do anything for 0.8.1, but maybe for the follow-on release. At the very least I'd like to make usage optional via the configuration.

**Comment by bsweeney** [comment] 2017-11-20 02:44
Merged a fix for IMagick issues in commit c68484c. If anyone can confirm the issue is resolved that would be great. The update will be included in 0.8.2.

**Closed** 2017-11-21 04:27 UTC
Labels: bug, imported, Priority-Medium
