### ISSUE TITLE
thead is repeating every page but tfoot doesn't, how to repeat tfoot?

### ISSUE THREAD

**Issue by CM1990** [dompdf/dompdf#1747] opened 2018-06-06 09:28 UTC

**Comment by shaiby** [comment] 2018-06-07 17:39
To repeat footer, on every page, I used a div that have position fixed and at very bottom of page....This way that div is use to repeat on every page as footer.

**Comment by simonberger** [comment] 2020-03-01 18:42
Duplicate of #25

**Closed by simonberger** 2020-03-01 18:42 UTC
