### ISSUE TITLE
Allow to specify local path for styles

### ISSUE THREAD

**Issue by ghost** [dompdf/dompdf#2098] opened 2020-02-24 15:08 UTC
According to comments in `Dompdf` class `$protocol` could be `file://`.

```
    /**
     * Protcol used to request file (file://, http://, etc)
     *
     * @var string
     */
    private $protocol;
```

The problem is that `build_url` function does not take `file://` protocol into account for relative paths.

**Comment by ytsurk** [comment] 2020-04-08 15:29
This patch helped me too to use files directly from the filesystem in a container environment. (https://www.drupal.org/project/entity_print/issues/2865185)

**Comment by bsweeney** [comment] 2020-05-03 20:21
Looks like a straightforward enough change. We'll review the PR and get back to you.

**Comment by bsweeney** [comment] 2020-08-02 19:24
Looking at this again, in what situation is the current logic problematic? Are we talking protocol-specified local paths such as `file://images/example.jpg`?

**Comment by ytsurk** [comment] 2020-08-03 08:31
In my case, running in docker w/o knowing the url/ip of the localhost (thus the desired file(s) could not be retrieved), switching from http(s):// to the file:// protocol was a painless solution that made the setup working.

**Comment by dealancer** [comment] 2020-09-03 20:16
@bsweeney any updates on this?

**Comment by bsweeney** [comment] 2020-09-04 13:28
I'm not sure of the exact nature of the issue. There are some changes in the next release that may address the issue. I had to make some changes to resource handling that included local resource handling. If anyone is able to test out what's in the master branch I'd appreciate it. The release will be posted in a day or so.

**Comment by ytsurk** [comment] 2020-10-16 15:38
I now tested. The issue remains and the proposed patch (https://github.com/dompdf/dompdf/pull/2099/commits/82456fd86db4e4b81549dd28eda6d1cbfd6e2850) still solves the problem.

@bsweeney

"We"/the Drupal module/or simply maybe also others ;) use the base_path also with the file:// protocol, whereas dompdf does not.

The question now is, is this by intention, then we will change in the Drupal module and others need to follow, or can we change dompdf to use the base_path also with the file:// protocol, then this merge request should go in!

**Comment by bsweeney** [comment] 2020-12-16 04:57
I'm still unclear on where the issue is here. Dompdf does support file-protocol for the base and Dompdf also utilizes the base properties to build out a relative URL.

On top of that I think there may be some confusion about what the base properties do. The base properties do not set a root against which URLs are set, they act more like the base href you would provide in an HTML document.

If I'm misunderstanding the issue please post back with a more detailed example.

**Comment by dealancer** [comment] 2020-12-16 05:07
@bsweeney,

Which properties you need to set in order to make relative paths work? Are you taking about following methods?

```
$dompdf
->setBasePath(DRUPAL_ROOT)
->setProtocol('file://');
```

If so, relative paths still do not work, but once you apply patch they work ok.

**Comment by bsweeney** [comment] 2020-12-16 13:49
What relative paths? I've tried the following and it works as expected:

```
<style>
    #bg {
        background-image: url(images/ants.jpg);
        height: 100px;
        width: 100px;
    }
</style>

<img src="images/ants.jpg">

<div style="background-image: url(images/ants.jpg); height: 100px; width: 100px;"></div>

<div id="bg"></div>
```

If you're seeing something different I'll need a fuller example to help determine where the issue lies.

**Comment by ytsurk** [comment] 2020-12-16 14:49
We're not talking about image paths here, but paths for fe. included CSS files, like

`<link rel="stylesheet" media="all" href="/sites/default/files/css/css_KcQcd4uYXt0AXoan06HdneZUwwMikRY5-MRvokjGNuA.css">`
or
`<style type="text/css" media="all">
@import url("https://example.com/themes/custom/yummy/css/system.base.css?qlff5h");
</style>`
or (if the file protocol is a choice)
`<link rel="stylesheet" media="all" href="file:///var/www/example.com/docroot/sites/default/files/css/css_KcQcd4uYXt0AXoan06HdneZUwwMikRY5-MRvokjGNuA.css">`

**Comment by bsweeney** [comment] 2020-12-16 15:13
Only the first one in your examples is not fully qualified, but they should all work. But I believe what you're trying to get at is that the first example doesn't take into account the base path. And that's to be expected because the first example is _not_ relative to the base href, it's relative to the root of the current domain. So if you're loading from the local filesystem it would be relative to the root of the filesystem, not to what is specified by the base href.

It's best to think of Dompdf as a web browser and not as an extension of your framework. If you loaded the same document with, say, wkhtmltopdf, you'd get the same results. Though the actual results may vary on local filesystems because of how paths are interpreted by various application (for example, Firefox on Windows 10 interprets "/" as being above the drive specification so you also have to specify the drive).

I think what you're looking for is a way to modify how root references are interpreted, and that's not something Dompdf allows for at present. I was looking to see if there's a way to reinterpret "/" using a stream context, but I don't see anything helpful there. You should look to see if there's a way to tell your framework to render the full path rather than a path starting from the document root.

**Comment by ytsurk** [comment] 2020-12-16 15:39
So - to answer my question from https://github.com/dompdf/dompdf/issues/2098#issuecomment-710121474 above:

> The question now is, is this by intention, then we will change in the Drupal module and others need to follow, or can we change dompdf to use the base_path also with the file:// protocol, then the #2269 should go in!

We can say, adapting root references will not be in the scope dompdf for now. Workaround(s) for the use cases we have, need to be handled by the Drupal module. Right?

**Comment by bsweeney** [comment] 2020-12-16 16:45
For now handled in the Drupal module. I have some thoughts about how to accommodate this need but I we'll push to address in the next release. I need to do some investigative work to see how to best accommodate the need. I'm thinking through some kind of callback or event. Maybe a custom stream wrapper option that allows you to manipulate a request before Dompdf executes it.

**Comment by ytsurk** [comment] 2020-12-16 17:06
Thank you for the insights :+1:

**Comment by bsweeney** [comment] 2023-02-07 15:01
I'm closing this issue because Dompdf is, as far as I know, working as intended and I don't think we'll do any work to address the specific request in the base logic.

However, I'm still keen on creating resource resolvers so I created an issue to track work on that feature (#3133).

**Closed by bsweeney** 2023-02-07 15:01 UTC
Labels: bug
