### ISSUE TITLE
Styling body with inline-block causes block-level parent exception

### ISSUE THREAD

**Issue by MichaelEugeneYuen** [dompdf/dompdf#1560] opened 2017-09-30 15:35 UTC
Applying inline-block to body tag will cause following errors:

```
Fatal error: Uncaught Dompdf\Exception: No block-level parent found. Not good. in D:\server_root\dompdf\dompdf\src\Positioner\Inline.php:45 Stack trace: #0 D:\server_root\dompdf\dompdf\src\FrameDecorator\AbstractFrameDecorator.php(873): Dompdf\Positioner\Inline->position(Object(Dompdf\FrameDecorator\Block)) #1 D:\server_root\dompdf\dompdf\src\FrameReflower\Block.php(806): Dompdf\FrameDecorator\AbstractFrameDecorator->position() #2 D:\server_root\dompdf\dompdf\src\FrameDecorator\AbstractFrameDecorator.php(894): Dompdf\FrameReflower\Block->reflow(NULL) #3 D:\server_root\dompdf\dompdf\src\FrameReflower\Page.php(141): Dompdf\FrameDecorator\AbstractFrameDecorator->reflow() #4 D:\server_root\dompdf\dompdf\src\FrameDecorator\AbstractFrameDecorator.php(894): Dompdf\FrameReflower\Page->reflow(NULL) #5 D:\server_root\dompdf\dompdf\src\Dompdf.php(832): Dompdf\FrameDecorator\AbstractFrameDecorator->reflow() #6 D:\server_root\dompdf\index.php(24): Dompdf\Dompdf->render() #7 {main} thrown in D:\server_root\dompdf\dompdf\src\Positioner\Inline.php on line 45
```

I ended up using a wrapper with inline-block to solve the issue:

```
<style>
.wrapper {
display: inline-block;
width: 100%;
}
</style>

<body>
<div class="wrapper">
<!-- content here-->
</div>
</body>
```

**Comment by bsweeney** [comment] 2017-09-30 18:16
Just curious, what is the goal of using that kind of styling on the body element?

Because of what dompdf needs to successfully process the document as a temporary work around we'll probably make the default display styling on the body element `!important`. It won't prevent someone from over-riding the styling, but should make it less likely that anyone will encounter this error.

**Comment by MichaelEugeneYuen** [comment] 2017-09-30 18:39
I was trying to create an html out as close as the pdf output. So, I created a pdf.css like this:

```
* {
	margin: 0;
	box-sizing: border-box;
}

html {
	padding-top: 10px;
	background: #e6e6e6;
	text-align: center;
}

body {
	display: inline-block;
	width: 730px;
	font-family: 'Droid', 'Helvetica';
	font-size: 14px;
	padding: 30px 40px;
	text-align: left;
	margin: 0 auto;
	background-color: #FFF;
}
```
This way, float element will be in the white background.

![image](https://user-images.githubusercontent.com/25918819/31048537-952841fc-a651-11e7-8c3b-6034a8b629c1.png)

**Comment by MichaelEugeneYuen** [comment] 2017-09-30 18:46
Simply what to report this issue to you so that you can ignore the body styling, particularly inline-block to prevent crash.

As long as a wrapper with display: inline-block is working, I am cool with it.

That's why I need a pdf.css just for the purpose of it. Knowing what can be applied and what no.

Thanks for the great dompdf!

**Comment by epreston** [comment] 2017-10-09 09:25
I found the issue and the fix for this.  The default DOM processor does not remove `#text` child nodes in nodes that should not have them.

When the HTML 5 processor is loaded, it does have this logic.  See below:
https://github.com/dompdf/dompdf/blob/ac40be1a7a5efbb4a905167eb4a0fcc89687c2e9/src/Dompdf.php#L473

Replicating this logic, for the default DOM processor appears to fix the issues.  I placed it after this line.
https://github.com/dompdf/dompdf/blob/ac40be1a7a5efbb4a905167eb4a0fcc89687c2e9/src/Dompdf.php#L491

Took most of the day to tack down.  Hope this helps @bsweeney

**Comment by neoteknic** [comment] 2017-10-20 09:39
Same problem, libxml2 related.
have to use libxml2-2.9-.4 crash on 2.9.5 and 2.9.6
Gentoo , php-fpm 7.1.10, Laravel 5.5.18

emerge =dev-libs/libxml2-2.9.4-r3
to fix on gentoo then restart php-fpm
Add >=dev-libs/libxml2-2.9.5 in /etc/portage/package.mask

**Comment by epreston** [comment] 2017-10-20 09:49
Resolution is above.  Some versions of libxml2 are treating "newline" characters between elements as "text" elements and adding it to the DOM.  Other versions are not.  When it adds the "text" elements to places its not allowed, like in "head" elements, it creates this problem.

Their are two code paths, one which has this correction and one that does not.  If you use the the HTML5 parser, it will strip them out after parsing but before generating the nodes for display.  The code submitted above adds this correction to both code paths.  I think it's a good compromise because we can't always inline the HTML before it is parsed but we can remove invalid and empty elements that may break the node render tree.

I don't have an immidiate requirement for a specific version of libxml2 but, I'd like to not worry about it for my project.

**Comment by bkilshaw** [comment] 2017-10-21 21:10
It appears to be an issue with all whitespace between elements not just newlines.

**Comment by bsweeney** [comment] 2017-10-24 01:05
The white space issue outside the body should be addressed by #1570. I still need to update the default stylesheet to better address the body styling issue. It won't be a definitive fix but it should help.

I still need to look into whether white space between other elements is an issue. I have not seen that confirmed anywhere else. @bkilshaw do you have a sample HTML document?

**Comment by titansoftime** [comment] 2017-12-07 17:37
FYI, when updating from PHP 7.1.7 to 7.1.12 I got this error.

I had to revert to 7.1.7 =[

**Comment by Riyazshk** [comment] 2018-05-09 15:48
Problem has been solved i just remove my <body> and <html> tag and meta tag .. and i got my output !

**Comment by LiamMcArthur** [comment] 2018-05-25 09:11
@epreston this solved my problem but I'm a little confused. I'm already on the latest version of Dompdf but that replicated code doesn't exist in my else statement.

**Comment by epreston** [comment] 2018-05-26 02:48
Are you on 8+ ?  The links above will take you to a version where it was not introduced.

I see it in master at line 493 in https://github.com/dompdf/dompdf/blob/master/src/Dompdf.php

**Comment by praideal** [comment] 2019-07-29 12:28
It worked after I removed spaces between HTML, Head and body tags. I put all in single line.

**Comment by nzrubin** [comment] 2020-08-11 02:58
I tried removing spaces and white spaces, I guess I just couldn't locate all of them
so instead I minimized the HTML file (PDF template) and it worked

**Comment by bsweeney** [comment] 2022-03-25 12:30
I believe the original issue is addressed? At least, I was unable to reproduce. If anyone is still experiencing the issue let us know.

**Closed by bsweeney** 2022-03-25 12:30 UTC
Labels: bug, On Deck
