### ISSUE TITLE
Call to a member function split() on a non-object

### ISSUE THREAD

**Issue by jamieburchell** [dompdf/dompdf#623] opened 2013-04-19 16:03 UTC
Hi

Using the trunk version of dompdf with a single table spanning 2 pages I receive the fatal error:

Call to a member function split() on a non-object ... dompdf\include\page_frame_decorator.cls.php on line 534

Sample HTML
http://www.jamieburchell.com/dompdf/fatal-split.htm

Platform:
Windows 7 php 5.2.17

This does not seem to happen in 0.6.0b3

Regards,

Jamie

**Comment by DerDu** [comment] 2016-04-07 15:16
Same here... +1

19 Apr 2013 ?? - ITS TIME TO FIX THIS

**Comment by bsweeney** [comment] 2016-04-08 03:19
@DerDu sample code is the best way to help us help you. So I think the reason I wasn't able to reproduce the issue is that I typically run with the HTML5 parser enabled. When I turned disabled that library dompdf threw the noted exception.

It looks like the main cause of the issue is the white space between the cells. When I enable the HTML5 parser the space is removed and the document render just fine. So, for now, while not ideal, you can try removing any space from between your table (table, tr, td, etc.) elements. Or maybe just try using the HTML5 parser.

The changes suggested in #1125 will prevent the exception from being thrown so that'll be pulled in the for the 0.7.0 release. We'll try to fully address the issue for 0.7.1.

**Comment by bsweeney** [comment] 2016-04-08 03:19
I'm also wondering if commit 2137e2b8e26e3ea85535080f48abc017e2dc7b40 could be relevant.

**Comment by bsweeney** [comment] 2017-01-16 16:57
No recent feedback, and so far as I can tell the issue seems to be addressed in the latest develop branch. Closing for now unless further info is incoming.

**Closed by bsweeney** 2017-01-16 16:57 UTC
Labels: bug
