### ISSUE TITLE
While using Colspan, border-right of the last column disappears

### ISSUE THREAD

**Issue by Carlitta87** [dompdf/dompdf#904] opened 2015-02-16 18:16 UTC
When i have multiple columns in one row, the last column has no right border. In this instance, i was using 33% colspan in a row. I read somewhere that it might be because i am using percentage but with pt and px, i still get the same result. I also used 50% in another row that works fine. What am I doing wrong?
![screen shot 2015-02-16 at 1 16 48 pm](https://cloud.githubusercontent.com/assets/2539915/6217112/91197326-b5de-11e4-87a0-b37bf7bb873a.png)

code snippet
![screen shot 2015-02-16 at 1 22 54 pm](https://cloud.githubusercontent.com/assets/2539915/6217155/f1799f0c-b5de-11e4-84e2-72f24264ba00.png)

**Comment by bsweeney** [comment] 2015-03-03 04:10
First, I think you mean to use `width` instead of `colspan`.

Second, I was unable to reproduce your issue with the small code sample you provided. What works best is to post with the issue or link to a full code sample that exhibits the problem. Preferably cut down to the smallest amount of code necessary (lest it take more time to debug the issue).

**Comment by bsweeney** [comment] 2020-11-24 14:13
Closing unless additional info can be provided. There was an issue with table border rendering around spanned cells (#1033) that has been addressed that perhaps fixes this issue.

**Closed by bsweeney** 2020-11-24 14:13 UTC
Labels: tables

**Comment by bsweeney** [comment] 2025-07-23 00:42
Ah, thank you for the update. There's a related issue for rowspan (see #2307). Since that one is still open go ahead and watch it for updates. Expecting the fix would be to cap rowspan/colspan to not overflow the table boundary.
