### ISSUE TITLE
underline the line is not quite below

### ISSUE THREAD

**Issue by mfeske** [dompdf/dompdf#1041] opened 2015-10-12 08:17 UTC
When using the beta version I made a mistake is noticed. When using underline the line is not quite below the font and intersects this part on.

**Comment by bsweeney** [comment] 2015-10-13 14:20
Similar problems have been reported in the past (#454, #609, #846). You might try the advice from #846:

> if you modify the font metrics file (UFM) you can tweak the underline position by changing the value of `UnderlinePosition`.

**Comment by mfeske** [comment] 2015-10-15 08:09
but in f45.ttf and Lato-Regular.ttf theire is no UnderlinePosition

**Comment by bsweeney** [comment] 2018-06-27 02:07
Would need additional info, but I believe this will be fixed in an upcoming release. Closing as a duplicate of #609. Please follow that issue for updates.

**Closed by bsweeney** 2018-06-27 02:07 UTC
Labels: bug, duplicate, font-handling
