### ISSUE TITLE
Setting element height/width attribute to "auto" results in translation to "autopx"

### ISSUE THREAD

**Issue by antonfries** [dompdf/dompdf#2296] opened 2020-11-16 14:18 UTC
In 0.8.5. we used e.g. width=100% and height="auto" that worked. But with the update to 0.8.6 it doesn't render the image, if there is a height="auto", just omitting that and only specifying width=100% does its job, but costed me some debugging.
![2020-11-16_15h15_05](https://user-images.githubusercontent.com/49792220/99262933-d570c700-281e-11eb-83c6-46368b989d02.png)
![2020-11-11_14h43_40](https://user-images.githubusercontent.com/49792220/99262974-e3264c80-281e-11eb-869d-0524ff232fb0.png)
However it does there an "autopx" and compare that with "auto" 🤔

**Comment by bsweeney** [comment] 2020-11-16 21:54
Thanks for the report ... looks like possibly a bug in some logic that parses the length value, appending "px" to the end without regard for whether or not the value is numeric.

**Comment by bsweeney** [comment] 2020-11-16 22:06
Hold up ... you're setting the height _attribute_ to "auto"? More than likely "autopx" was being generated previously as well. Attributes are translated to styles in the attribute translator class. You can see that the [mapping for img height](https://github.com/dompdf/dompdf/blob/v0.8.6/src/Css/AttributeTranslator.php#L36) is "{val}px" and has pretty much always been that way.

I'd have to look at the history to see what change impacted how that height value is being parsed.

**Comment by bsweeney** [comment] 2021-06-22 14:23
closing as a duplicate of #2240, follow there for updates

**Closed by bsweeney** 2021-06-22 14:23 UTC
Labels: bug, css, duplicate
