### ISSUE TITLE
Generated content missing in font subset

### ISSUE THREAD

**Issue by Paktas** [dompdf/dompdf#750] opened 2013-12-16 21:46 UTC
I've recently setup DOMPDF_ENABLE_FONTSUBSETTING and installed/copied fresh php-font-lib to dompdf/lib/php-font-lib/.
It looks to have decreased the PDF file size (6 times), however some characters didn't end up in the subset.
I am using &lt;ol&gt;&lt;li&gt; entries styled to bold together with counter on CSS:

```
OL { counter-reset: item;}
OL LI { display: block; font-weight:bold; }
OL LI:before { content: counters(item, ".") ". "; counter-increment: item }
```

Seems like the prefixed numbers for &lt;li&gt; that are created with CSS counter do not end up in the font subset. It's showing uknown symbol for that bold-missing character in generated PDF.

For the testing purpose manually adding some of the missing numbers somewhere in html/text in bold - fixes the issue, counter generated list numbers AND entered manually in the body show up fine in li's inside pdf (as per screenshot below).
![numbers on counter](https://f.cloud.github.com/assets/6200695/1759403/e0ecca10-669d-11e3-84e2-177d72684294.JPG)
Workaround is to put bold numbers 0 through 9 in hidden span, but this doesn't look right.

Removing the subsetting option in dompdf - all characters work like a charm (and generates a big pdf file as well).

Hope this can be fixed on the road to better dompdf font subsetting.

NOTE: tested on PHP 5.2.4, linux, newest github versions of dompdf and php-font-lib.

**Comment by bsweeney** [comment] 2017-02-02 03:36
Additional improvements to content-declared text was added in commit 27ce2db2.

**Comment by MarkMaldaba** [comment] 2019-08-12 14:27
What's the status of this ticket.  It is marked as 'On Deck' and was slated for 0.8.1, but that was over 2 years ago.

I can see there is some code relating to this issue, present in 0.8.3.  I can also see that the `page_text()` function (and `text()`, presumably) don't have their characters included in the font subsetting yet.

What is needed to resolve this ticket (and in particular to get it working for `text()`/`page_text()`, which are the main issues for my use-cases)?  Is there anything I or anyone else can do to help?

**Comment by bsweeney** [comment] 2019-09-09 02:19
Status is that it is still on deck, and will remain so until someone submits a pull request or someone on the team (pretty much just me right now) is able to work on the issue.

I do not believe the issue is particularly difficult to resolve, though it does require changes in a number of locations (and the time to make those changes). The font subsetting logic should be removed from Dompdf completely and be handled entirely within Cpdf. There are a few potential ways to do this but I believe the way I would do this would be to modify the Cpdf text methods to add characters to the font subset cache (`Cpdf::stringSubsets`) then move the actual sub-setting code out of `Cpdf::selectFont` and into `Cpdf::o__font` for the "output" action. This is a high-level overview, I haven't fully reviewed this idea to see if there are other changes that would also need to be made.

**Comment by MarkMaldaba** [comment] 2019-09-09 10:40
Thanks for the update.

Is Cpdf part of DomPDF, or a separate project?  If the latter, does an upstream ticket need to be created or is it just a matter of updating DomPDF to use existing functionality?

**Comment by bsweeney** [comment] 2019-09-14 18:00
The version of CPDF we use is part of Dompdf.

**Comment by bsweeney** [comment] 2020-06-30 02:01
This should be addressed with the next release. Font subset functionality is moved from Dompdf to the CPDF library.

**Closed by bsweeney** 2020-06-30 02:01 UTC
Labels: font-handling
