### ISSUE TITLE
SVG fill-opacity=0.2 not work

### ISSUE THREAD

**Issue by xerron** [dompdf/dompdf#2226] opened 2020-09-06 15:17 UTC
I, Try:

```svg
<svg
    xmlns:dc="http://purl.org/dc/elements/1.1/"
    xmlns:cc="http://creativecommons.org/ns#"
    xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
    xmlns:svg="http://www.w3.org/2000/svg"
    xmlns="http://www.w3.org/2000/svg"
    id="svg8"
    version="1.1"
    viewBox="0 0 114.083 30.97118"
    height="30.97118mm"
    width="114.083mm">
    <defs
        id="defs2" />
    <g
        transform="translate(38.539526,-51.48077)"
        id="layer1">
        <ellipse
            ry="6.8153729"
            rx="15.768902"
            cy="59.296143"
            cx="37.167988"
            id="path28"
            style="fill:#ffffff;fill-opacity:0.2;stroke-width:0.26458332" />
    </g>
</svg>
```

Result in:

ErrorException: Trying to access array offset on value of type null in file /home/uwu/Repos/caleidos/veri_eva/arq1/evaluativa/vendor/dompdf/dompdf/lib/Cpdf.php on line 3226

Why?.

Last iteration of setFillTransparency:  $this->currentFillTransparency is null, in class Cpdf.php

I resolve with: Line 3226 in class Cpdf.php

```php
 if(is_null($this->currentFillTransparency)) {
            $this->currentFillTransparency = [];
        }

        if ($mode === (key_exists('mode', $this->currentFillTransparency) ? $this->currentFillTransparency['mode'] : '') &&
            $opacity == (key_exists('opacity', $this->currentFillTransparency) ? $this->currentFillTransparency["opacity"] : '')
        ) {
            return;
        }
```
And Work; Please set the change. Thank.

**Comment by xerron** [comment] 2020-09-06 16:10
#2227

**Comment by bsweeney** [comment] 2020-09-07 01:08
Which version of Dompdf are you using? So far I'm unable to reproduce the issue.

Of note is that the version of CPDF bundled with Dompdf should not be doing SVG parsing. There's a separate version of CPDF used by the SVG parsing library (php-svg-lib). More than likely your issue should be addressed in that project. Perhaps you are running an older version of Dompdf that does not namespace the bundled library? That was added in Dompdf 0.8.4.

It's possible a similar issue exists in Dompdf, but we would prefer to be able to reproduce the issue in order to ensure we properly address it.

**Comment by xerron** [comment] 2020-09-10 09:07
I use DomPDF 0.8.5, and php 7.4

**Comment by bsweeney** [comment] 2020-09-10 12:21
I'm still unable to reproduce the issue. CPDF initializes with a value in that property and I do not see where it would be set to null by Dompdf. I don't disagree that the change you make adds safety to the method but I want to try and understand what's happening.

**Comment by ghidoz** [comment] 2021-03-30 09:46
I also have an SVG in my document and now that I upgraded to PHP 7.4, it throws the same error. 
@bsweeney can you please merge @xerron's PR?

There's also a PR on the  php-svg-lib repo, but it looks like not maintained anymore: https://github.com/PhenX/php-svg-lib/issues/60

**Comment by feltoar** [comment] 2021-04-13 23:23
Another vote for @xerron's PR to be merged

Regarding @bsweeney's comment about the php-svg-lib project. Changing the code in `vendor/dompdf/dompdf/Cpdf.php` fixed the problem. While changing the code in `phenx/php-svg-lib/src/Svg/Surface/CPdf.php` had no effect.

This was with dompdf 1.0.2 (PHP 7.4 on Laravel Homestead 11.4.0). The SVG itself was created with Inkscape. I would link a copy but it is somewhat sensitive.

**Comment by bsweeney** [comment] 2021-05-10 19:06
Thanks for the follow up about making that change. I'll go ahead and schedule this for the next release. I'm still not sure what's going on here since svg rendering should be taking place in the CPDF instance inside php-svg-lib. I'll update the code in that library at the same time just go be safe.

**Closed** 2021-07-13 01:43 UTC
Labels: bug, dependencies
