### ISSUE TITLE
HTML comments in table prevent output

### ISSUE THREAD

**Issue by lightstream** [dompdf/dompdf#993] opened 2015-07-23 13:40 UTC
Thanks for your work on this great project. The results are even better than I'd expected!
I also wanted to let you know about a problem I've encountered when creating PDFs containing tables that have HTML comments in them.
In the example below, the table rows in the tbody do not appear in the PDF unless the HTML comments are stripped out. I'm using the develop branch installed via Composer.
The HTML table is a bit of a mess, because it's produced by a framework.
```php
$html = '<table id="table" class="paginatedTable" ref="/">
<col id="table_column_Description"/><col id="table_column_price"/>
<thead>

	<!-- Show the paginator at the top of the table if requested -->


	<!-- Display the column headers and sort selectors -->
	<tr>

			<th class=" " id="table_header_Description">
				<!-- for non-sortable columns just show the title -->
				<span class="columnTitle">Description</span>


			</th>

			<th class=" " id="table_header_price">
				<!-- for non-sortable columns just show the title -->
				<span class="columnTitle">Price</span>


			</th>

	</tr>
</thead>

<!-- display the data -->
<tbody>
	<tr>

		<td class="table_cell_Description">muppetfrenzy</td>

		<td class="table_cell_price">78.35</td>

		</tr><tr>

		<td class="table_cell_Description">muppetparty</td>

		<td class="table_cell_price">78.35</td>

		</tr><tr>

		<td class="table_cell_Description">muppetteam</td>

		<td class="table_cell_price">78.35</td>

	</tr>
</tbody>

<!-- Show the paginator at the bottom of the table if requested -->
<tfoot>

</tfoot>
</table>';

// Instantiate DOMPDF
$dompdf = new Dompdf\Dompdf();
$dompdf->load_html($html);
// Uncomment line below to remove the comments, and the table will render correctly
//$dompdf->load_html(preg_replace('/<!--.*-->/', '', $html));
$dompdf->render();
$dompdf->stream('table.pdf');
```

**Comment by bsweeney** [comment] 2015-07-24 01:20
I do see that. I wonder, perhaps, if the issue is related to #895 (though I don't see the cited error).

**Comment by lightstream** [comment] 2015-07-28 20:58
I had a chance to play around with it some more, and the problem appears to be that if there's a comment before a `<tbody>`, `<thead>`, `<tfoot>` or `<tr>`, then that element will not appear in the output. 

eg remove just the comment `<!-- display the data -->` which appears before `<tbody>` and the table content appears correctly.

or add a comment before the `<thead>` or any `<tr>`, and that element will no longer appear in the PDF.

Not sure if this is helpful for you!

If I can get the time, I will try to investigate further.

**Comment by bsweeney** [comment] 2015-07-29 01:20
Thanks for the update. I haven't looked at your issue yes, but a pull request (#996) was recently submitted that might help. I'm planning to incorporate it fairly quickly.

**Comment by lightstream** [comment] 2015-07-29 08:17
It does look like that could help - when I traced through the code yesterday, everything seemed to be intact up til the FrameTree gets created, which is where I lost track of it!

However it didn't help when I tried removing the content preceding the comment in my example (the content just being whitespace in this case).

I did discover that the problem seems to be that the element following a comment disappears - ie two comments one after the other cancel each other out, three comments in a row have the same effect as a single one etc

I'll wait til you merge that pull request and if the problem persists, I'll see if I can dig into it a bit more deeply.

**Comment by bsweeney** [comment] 2015-09-12 16:34
FYI, develop has been merged with the change.

**Comment by bsweeney** [comment] 2015-09-16 17:42
Not sure what was introduced between 0.6.1 and 0.7 to cause the issue but the cited change appears to have addressed it.

**Closed by bsweeney** 2015-09-16 17:42 UTC
Labels: bug

**Comment by lightstream** [comment] 2015-09-21 10:49
I can confirm that this issue has been resolved.

Thanks Brian.
