### ISSUE TITLE
Images are not centered correctly

### ISSUE THREAD

**Issue by HendrikRoehm** [dompdf/dompdf#1949] opened 2019-06-17 15:59 UTC
The following seems to be a bug to me. I have an image that should be centered horizontally. However, in the generated pdf file, it is left-aligned. When opening the same html code with a browser, the image is shown centered.

I have created a minimal working example:

generatePdf.php:
```php
<?php

require_once "vendor/autoload.php";

// reference the Dompdf namespace
use Dompdf\Dompdf;

// instantiate and use the dompdf class
$dompdf = new Dompdf();
$html = file_get_contents("testPdf.html");
$dompdf->loadHtml($html);
$dompdf->setPaper('A4');
$dompdf->render();
$output = $dompdf->output();
file_put_contents("testPdf.pdf", $output);
```
testPdf.html:
```html
<html>
    <head>
        <style>
            .center {
                text-align: center;
            }
            .center img {
                display: block;
                margin-left: auto;
                margin-right: auto;
            }
        </style>
    </head>
    <body>
        <div class="center">
            <h1>H1</h1>
            <img src="wikipedia-Png-logo.png">
        </div>
    </body>
</html>
```

The image is a local copy of https://upload.wikimedia.org/wikipedia/de/thumb/b/bb/Png-logo.png/160px-Png-logo.png

I just installed dompdf via composer (version 0.8.3) and run `php generatePdf.php`.

There seem to be some very open issues which are related: #861, #1420 .

**Comment by wbswbs** [comment] 2019-06-17 16:06
Just now I am searching for the same Bug.
There is one workaround: Set Text-align: center to the parent element, but this is not, what we really want.

**Comment by HendrikRoehm** [comment] 2019-06-17 16:12
haha, nice. I also just found the same workaround one minute ago: create an additional div container as a wrapper for the image and align this div. However, I agree with you that the behaviour in the minimal example is not the intended one.

**Comment by wbswbs** [comment] 2019-06-17 16:28
Which will not work, when the img is in a p Paragraph, Div is not allowed inside.
One solution seems to be, to center everything in the p, or divide the content into other nodes and image node.
With this, ist is not possible to have floating Text around a centered Image, which works well with float:left and float:right.

**Comment by wbswbs** [comment] 2019-06-17 16:43
This example has the image centered in PDF, but not in HTML:

http://eclecticgeek.com/dompdf/debug.php?identifier=36dd28304078655bf6f5bcf42304519d

<html>
    <head>
        <style>
            .center {
                text-align: center;
            }
            .center img {
                display: block;
            }
        </style>
    </head>
    <body>
        <div class="center">
            <h1>H1</h1>
            <img src="https://upload.wikimedia.org/wikipedia/de/thumb/b/bb/Png-logo.png/160px-Png-logo.png">
        </div>
    </body>
</html>

**Comment by bsweeney** [comment] 2019-06-22 21:02
I want to say the first example is an issue with auto margins applied to images. I seem to recall something similar though I couldn't track down the relevant issue.

Generally, Dompdf does not like the application of different display styling to images because of the way they are parsed. it's possible the rendering of the two samples is a side affect of that issue.

**Comment by wbswbs** [comment] 2019-06-24 08:43
> Generally, Dompdf does not like the application of different display styling to images because of the way they are parsed. it's possible the rendering of the two samples is a side affect of that issue.

What is the prefered order from Dompdf ?

Inline Style over CSS Style?
Inner Style over Outer Style?

This would be CSS Standard, right?

**Comment by HendrikRoehm** [comment] 2019-06-24 08:52
It seems to me that at least a small comment in the documentation is necessary.

**Comment by bsweeney** [comment] 2019-06-25 00:06
The issue is not in how you write your styles, but actually changing the display type of the image (e.g. `img { display: block; }`). The display styling doesn't seem to break the image rendering in this case so I'm really just noting for reference.

**Comment by dennisameling** [comment] 2019-12-24 10:53
We're also affected by this issue. As a workaround, since we have dozens of images in our PDFs and all of them need to be centered, we wrap DIVs around all images in our PHP code with CSS class "aligncenter". It's ugly, but saved us tons of time, otherwise we had to change all content in our CMS which would have taken hours. Maybe this code can help someone else :)

```PHP
// Temp bugfix as images are not centered correctly in DOMPDF (see https://github.com/dompdf/dompdf/issues/1949)
// We wrap a DIV with class "aligncenter" around all images.
libxml_use_internal_errors(true);
$doc = new \DOMDocument();
$doc->loadHtml(mb_convert_encoding($html, 'HTML-ENTITIES', 'UTF-8'));

$xpath = new \DOMXPath($doc);
$imgTags  = $xpath->query(
    '//img'
);

foreach ($imgTags as $tag) {
    $div = $doc->createElement('div');
    $div->setAttribute('class', 'aligncenter');
    $tag->parentNode->insertBefore($div, $tag);
    $div->appendChild($tag);
}

$html = $doc->saveHTML();
libxml_use_internal_errors(false);
```

**Comment by jmvezic** [comment] 2020-02-04 09:10
> The issue is not in how you write your styles, but actually changing the display type of the image (e.g. `img { display: block; }`). The display styling doesn't seem to break the image rendering in this case so I'm really just noting for reference.

I haven't tinkered with the "display" of img and I still get the same bug, when imgs are in a paragraph that has text-align:center;

**Comment by inifahmi3** [comment] 2020-09-22 05:34
Hello
I've tried to position the image in the middle of the table component using inline css in the div

below is an example of part of the table components

`<td style="text-align: center">
                    <div style="background-image: url({{ asset('images/logo.png') }});
                                height: 80px;
                                background-size: contain;
                                background-position: center center;
                                background-repeat: no-repeat"></div>
                </td>`

here I am using
laravel = 5.8
barryvdh/laravel-dompdf = 0.8.6

**Comment by bsweeney** [comment] 2020-09-22 14:26
Except for the noted issues around auto margins and modification of the image display type, I'm able to center an image in a table cell without issue in 0.8.6.

**Comment by muhdtamrin** [comment] 2021-08-31 10:22
Same issue but just using a little trick to center the image. `.center {
    display: block;
    width: 10%;
    margin-left: 45%;
  }`
Hope will help someone.

**Comment by bsweeney** [comment] 2021-08-31 18:13
I tested a variety of samples and the following work with the latest release:

table background:
```
<table width="100%" border="1"><tr>
<td style="text-align: center"><div style="background-image: url(https://placekitten.com/200/200); height: 80px; background-size: contain; background-position: center center; background-repeat: no-repeat"></div> </td>
</tr></table>
```

text-align:
```
<div style="page-break-before: always; text-align: center; border: 1px solid black;"><img src="https://placekitten.com/200/200"></div>
```

inside auto-margin div with matching width:
```
<div style="page-break-before: always; width: 200px; margin: auto; border: 1px solid black;"><img src="https://placekitten.com/200/200"></div>
```

text-align with inline-block image:
```
<div style="page-break-before: always; text-align: center; border: 1px solid black;"><img src="https://placekitten.com/200/200" style="display: inline-block;"></div>
```

Only the following does not work:
```
<div style="page-break-before: always; border: 1px solid black;"><img src="https://placekitten.com/200/200" style="display: block; width: 200px; height: 200px; margin: auto;"></div>
```
which I believe is likely related to #1482.

As such I'm going to go ahead and close this issue unless the problem can be further isolated in a way that differentiates it from that issue.

**Closed by bsweeney** 2021-08-31 18:13 UTC
Labels: bug, layout
