### ISSUE TITLE
Table content overflowing off Page

### ISSUE THREAD

**Issue by chdonncha** [dompdf/dompdf#3495] opened 2024-07-16 09:20 UTC
When having large bodies of text in a table it will overflow off the bottom of the page and not carry on to the next page, as shown:
![image](https://github.com/user-attachments/assets/d0f1260f-596b-490a-bbd1-83534e96873f)

Using:
```html
        <table class="entry">
            <tr>
                <td class="label">
                    <span class="dottedUnderline">
                        {{ $label }}
                    </span>
                </td>
                <td class="value">
                    {{ $component }}
                </td>
            </tr>
        </table>
```

**Comment by bsweeney** [comment] 2024-07-21 15:32
It's true. I have started working on a fix though I do not yet have a timeline for release.

duplicate of #98

**Closed by bsweeney** 2024-07-21 15:32 UTC
Labels: duplicate
