### ISSUE TITLE
Image styled to render at page height/width not visible in output

### ISSUE THREAD

**Issue by bsweeney** [dompdf/dompdf#2631] opened 2021-11-04 15:51 UTC
The following renders as a blank document with the 1.1.0 release.

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        @page {
            size: 100px 75px;
            margin: 0px;
            padding: 0px;
        }
        body {
            margin: 0px;
        }
    </style>
</head>
<body>

    <img src="http://placekitten.com/500/375" style="width: 100%; height: 100%;">

</body>
</html>
```

**Comment by Nuranto** [comment] 2021-12-17 17:32
I'm not sure if this is linked to this issue, but there is image issues since last two releases, but I have troubles with images that are reduced to a very tiny size, when displayed on the end of a page, instead of being displayed on next page. Even a page break does not solve this. 
See those two examples to understand : 

1/ 
```
<html>
           <head>

           </head>
           <body>
           <div style="height:80%"></div>
           <div style="text-align: justify;">
           <img src="http://placekitten.com/500/375" style="max-width: 100%; max-height: 100%;">
           <img src="http://placekitten.com/500/375" style="max-width: 100%; max-height: 100%;">
           </div>
           </body>
           </html>
```

2/

```
<html>
           <head>

           </head>
           <body>
           <div style="height:90%"></div>
           <div style="text-align: justify;">
           <img src="http://placekitten.com/500/375" style="max-width: 100%; max-height: 100%;">
           <img src="http://placekitten.com/500/375" style="max-width: 100%; max-height: 100%;">
           </div>
           </body>
           </html>
```


Another, less critical, issue : 
```
<html>
           <head>

           </head>
           <body>
           <img src="http://placekitten.com/500/375">
           <img src="http://placekitten.com/500/375">
           <img src="http://placekitten.com/500/375">
           <img src="http://placekitten.com/500/375">
           <img src="http://placekitten.com/500/375">
           <img src="http://placekitten.com/500/375">
           </body>
           </html>
```

You'll see that page 3 does not display as page 1 and 2 (space between images)

**Comment by Mellthas** [comment] 2021-12-18 19:20
What looks like a regression in your first two samples is due to changes in whitespace handling for page breaks (see commit 3cb71d24df0741a6826dcd3673accc2501343adf). If you remove the whitespace between the div end tag and the body end tag, the rendering should be identical between version 1.0.2 or earlier and 1.1.0/1.1.1. The issue was masked previously: The whitespace at the end forced a page break before the div containing the images.

The issue with the small images is due to the containing block for the images being set to the remaining space on the first page. I think the containing-block height should instead be undefined in this case, as the parent div has `auto` height. The max height should have no effect then (see https://www.w3.org/TR/CSS21/visudet.html#min-max-heights). As such, a workaround would be removing the `max-height` declaration.

The original issue is slightly different as it is not about `max-height` but about `height`, which uses an unconventional code path to resolve percentage values, not checking the containing block. This should be solvable by simply consulting the containing block instead.

The last issue seems unrelated. It looks like it is caused by vertical alignment. Removing any whitespace between the image elements fixes rendering. Another workaround is to use `vertical-align: top` for the images.

**Comment by Mellthas** [comment] 2021-12-21 01:50
The original issue and the last sample by @Nuranto are fixed by the referenced PRs. I’ll create a new issue for the issue with the small images.

**Closed** 2022-01-09 11:18 UTC
Labels: bug, css, layout
