### ISSUE TITLE
Not processing <title> extended character set (Chinese)

### ISSUE THREAD

**Issue by NewLIST** [dompdf/dompdf#1488] opened 2017-07-07 15:39 UTC
When passing extended character set Chinese characters into the DOM <title>你好，世界</title> the parser replaces these characters with question marks. INSTEAD of replacing the characters with question marks, just pass them through if they don't cause an error.

**Comment by bsweeney** [comment] 2017-07-11 16:50
We'll have to look at what the (PDF 1.3) spec allows for this, but we will definitely look into this.

**Comment by simonberger** [comment] 2017-08-06 19:20
As far as I could reproduce this it works well on unicode fonts.
It just failed on encrypted documents because of a bug. This is fixed now.

Could you please retest on the current develop branch?
if you hadn't encryption activated you can skip this test.

If this still fails for you or you haven't used encryption. Some more questions or tests you could try:

- do you have Chinese characters also in your pdf content?
- If not could you test if they really render well? If they fail too you haven't included a font that can render those characters.

**Closed** 2017-11-04 13:11 UTC
Labels: enhancement
