### ISSUE TITLE
Release 0.8.4 doesn't render h1/h2/.../hX styles properly (bug)

### ISSUE THREAD

**Issue by jannakha** [dompdf/dompdf#2064] opened 2020-01-25 14:29 UTC
Hello!

In HTML I've got:

```
<div class="field-group-details">
    <h2>ROCKCOTE SPECIFICATIONS AND TECHNICAL INFORMATION RELATING TO PROJECT:</h2>
</div>
```

- if in styles.css I set h2 to 5rem, DOMPDF doesn't render `h2{font-size:5rem}`, in PDF it renders font size as default body font (there are no other h2 overrides) (all browsers render HTML page as expected with font size set to 5rem)
- if I update style to `.field-group-details h2 {font-size: 5rem}` it renders font size correctly in PDF
- `h1` doesn't render custom styles (just renders default body font) even with extra class

It was fine in 0.8.3, I haven't installed any other updates only 0.8.3 to 0.8.4.

**Comment by bsweeney** [comment] 2020-01-25 15:35
I'm not seeing the same thing using your minimal example.

```
<style>
.rem {font-size:5rem}
</style>

<div class="field-group-details">
    <h1>ROCKCOTE SPECIFICATIONS AND TECHNICAL INFORMATION RELATING TO PROJECT:</h1>
    <h1 class="rem">ROCKCOTE SPECIFICATIONS AND TECHNICAL INFORMATION RELATING TO PROJECT:</h1>
    <h2>ROCKCOTE SPECIFICATIONS AND TECHNICAL INFORMATION RELATING TO PROJECT:</h2>
    <h2 class="rem">ROCKCOTE SPECIFICATIONS AND TECHNICAL INFORMATION RELATING TO PROJECT:</h2>
    <p>ROCKCOTE SPECIFICATIONS AND TECHNICAL INFORMATION RELATING TO PROJECT:</p>
    <p class="rem">ROCKCOTE SPECIFICATIONS AND TECHNICAL INFORMATION RELATING TO PROJECT:</p>
</div>
```

Do you have a more complete example exhibiting the issue?

**Comment by newfylox** [comment] 2020-01-28 22:17
I am using [barryvdh/laravel-dompdf](https://github.com/barryvdh/laravel-dompdf) and it depends on this library. I did a `composer update` and it updated **dompdf** from 0.8.3 to 0.8.4 but I didn't notice it since it was not in my `composer.json` (but of course it was committed in my `composer.lock`). 

Since then, all my PDF were blank, images were loading but not texts. When I discovered it could be about that update (0.8.4), I required version 0.8.3 and all went back to normal.

I just wanted to let you know even if it doesn't help much about the real problem.

**Comment by acha5066** [comment] 2020-01-30 05:51
I'm experiencing the same thing as OP but I'm using 0.8.3. 

"h1 doesn't render custom styles (just renders default body font) even with extra class". 

This is also true for h2 and I would imagine would be the same for h3 through h6. 

In addition, the line heights are much larger in pdf output than they are in the page I'm generating the pdf from. 

Custom fonts work fine on any elements but for some reason not on headings.

**Comment by bsweeney** [comment] 2020-01-31 03:36
Without a reproducible sample it's hard to say what the issue is.

You can try out various renders here: http://eclecticgeek.com/dompdf/debug.php

One thing you could try would be to remove the font cache (dompdf_font_family_cache.php, in the font directory) and see if that helps.

**Comment by azaricstefan** [comment] 2020-02-24 00:37
My h1 which has special character like "č" is encoded as "?". I also noticed if I change style for h1 tag it doesn't apply at all.

**Closed** 2022-03-02 15:00 UTC
Labels: question
