### ISSUE TITLE
DomPDF base64 encode of addInfo values  

### ISSUE THREAD

**Issue by remosek** [dompdf/dompdf#1643] opened 2018-01-23 16:30 UTC
I am having an issue with DomPDF and base64_encode with setEncryption function.
This is a sample of my code.
`/ Render the HTML as PDF
    $dompdf->render();

    //Encode title into base64 and add it to PDF Meta
    $title_64 = base64_encode( $title );
    $dompdf->getCanvas()->get_cpdf()->addInfo( 'Subject' , $title_64 );

    //Locking pdf to allow printing only
    $dompdf->getCanvas()->get_cpdf()->setEncryption( '' , '' , array( 'print' ) );

    // Output the generated PDF to Browser
    $dompdf->stream( $post->post_name . ".pdf" , array( "Attachment" => TRUE ) );`

So pretty much what is happening once PDF is downloaded all meta data is missing.

As soon I remove base64_encode function that is wrapping $title Meta data is back.

Also if I keep base64_encode but I remove
`$dompdf->getCanvas()->get_cpdf()->setEncryption( '' , '' , array( 'print' ) );`
Everything seems to be working but I am able to modify PDF which I don't want.

As my end result I should be able only to print PDF which is what i have now + all Meta data to be
base64_encoded

Did anyone encounter similar issue ?

**Comment by JanSlabon** [comment] 2018-01-25 10:08
This is a bug in the CPDF class/version, which is used by DomPDF. The encrypted strings are not escaped correctly:

`/Producer` (Œa6Sq©åðÇ9Å—ÙÒ°Çl¡ÿÝøVóVÑª!Õñ¶7(Þýä¡)`

There's an open bracket near the end of the string, which is not escaped nor balanced.

The logic in [these lines](https://github.com/dompdf/dompdf/blob/master/lib/Cpdf.php#L1419) is faulty. The strings are escaped prior encryption which is simply wrong.

**Comment by remosek** [comment] 2018-01-31 09:27
Thanks JanSlabon for your replay, 

Do you know any solution that could solve my issue? I have been trying to figure it out on my own but didn't got further.

**Comment by JanSlabon** [comment] 2018-01-31 09:36
I don't know the internals of CPDF nor the filterText() method. It looks like a method which can do more than simply escaping. Anyhow the order is simply wrong and also the kind of unicode handling is faulty (IMHO)... Also encrypting an escaped string is faulty. So there is this issue but I'm unsure if this isn't spread through the whole code. This is sadly out of my scope, sorry.

**Comment by remosek** [comment] 2018-01-31 12:23
I had attempts base_64 encoding the pdf meta data and i Figured it out Creator / Subject meta data is breaking the whole thing. 

Thanks Jan For your help.

**Comment by bsweeney** [comment] 2021-12-03 19:48
This looks like a duplicate of #1541 we'll follow up there.

**Closed by bsweeney** 2021-12-03 19:48 UTC
Labels: bug, duplicate
