### ISSUE TITLE
a tag link is not working

### ISSUE THREAD

**Issue by xploregopi** [dompdf/dompdf#1571] opened 2017-10-09 10:54 UTC
Hi Friends,

The following code is not working.

```
<p class="bottom-line" style="margin-top:10px;"><span class="website"><a href="#" target="_blank">www.google.com</a></span></p>
```

 Problem: Same page link is working but not open the new window/tab

**Comment by Juventino96** [comment] 2017-10-13 15:21
I have the same thing.

**Comment by javfres** [comment] 2017-10-16 07:53
It's not working for me either. I'm using version 0.8.1. I'm including a small test code and the resulting pdf.

```php
<?php

require "vendor/autoload.php";
use Dompdf\Dompdf;

$dompdf = new Dompdf();
$dompdf->loadHtml("
<html>
	<body>
		<h1>Link not working :(</h1>
		<a href='http://www.google.com'>Link 1</a>
		<a href='www.google.com'>Link 2</a>
	</body>
</html>
");
$dompdf->render();
$output = $dompdf->output();
file_put_contents('test.pdf', $output);
```
[test.pdf](https://github.com/dompdf/dompdf/files/1386576/test.pdf)

**Comment by bsweeney** [comment] 2017-10-16 21:44
Seems to be two different issues here (please correct me if I'm wrong).

1. Links not working in 0.8.1. That's a duplicate of #1559.
2. Links not opening in a new tab. That's a duplicate of #1261.

**Closed by bsweeney** 2017-10-16 21:44 UTC
Labels: duplicate
