### ISSUE TITLE
No block level parent found

### ISSUE THREAD

**Issue by Alan-Safesmart** [dompdf/dompdf#1959] opened 2019-07-01 13:48 UTC
I am using an old version of the plugin 0.5.1 and I am receiving this error:

Fatal error: Uncaught exception 'DOMPDF_Exception' with message 'No block-level parent found. Not good.' in /var/www/web50/htdocs/system/library/dompdf/include/inline_positioner.cls.php:37

I have tried all the suggested steps, ie remove whitespace from html,body tags.

I have enabled the html5 parser even though I dont know if this works on the old version.

This has been working on an application for ages until the server was upgraded to easy apache 4.

Any ideas how I can fix it?

**Comment by MarkMaldaba** [comment] 2019-07-02 10:12
This is a duplicate of issue #1560 and #1935 and is caused by a libXML upgrade.  Various potential solutions are suggested in those linked threads, the recommended one being to upgrade to the latest version of DomPDF.

**Comment by bsweeney** [comment] 2019-07-09 01:23
There's no HTML5 parser in that version of Dompdf. You might try upgrading, there are many, many improvements. Beyond that I can only guess. Happy to try some pointers if you supply a sample HTML that breaks.

**Closed by bsweeney** 2019-07-09 01:23 UTC
Labels: bug, wontfix
